### ISSUE TITLE
:bug:  bug :  navigation tab is not working properly

### ISSUE THREAD

**Issue by aialok** [asyncapi/asyncapi-react#1008]
**Description**
- Navigation tab between schema and configuration is not working as expected.

**Expected Result**
- It should navigate properly between the schema tab and configuration tab. 

[Screencast from 2024-05-30 17-23-42.webm](https://github.com/asyncapi/asyncapi-react/assets/66772290/e9bdbe8a-d609-42a0-b7b1-1e3c4e5cfe78)

**Actual Result**

[Screencast from 2024-05-30 17-28-34.webm](https://github.com/asyncapi/asyncapi-react/assets/66772290/578f5fca-b689-4873-838c-30c69b0af6c6)

**Steps to Reproduce**

1. Go to the AsyncAPI website homepage.
2. Click on the configuration tab.
3. Click on the schema tab.
4. Try to navigate back to the configuration tab.

**Troubleshooting**

- I found there is issue in `tabIndex`. Basically in one of if statement we are checking `tabIndex` but `tabIndex` is value can equal to zero and `schema` tab tabIndex is zero so when navigating back to schema tab from configuration tab.  If statement is not working and hence navigation is not working.

**Comment by aialok** [comment]
I would love to work on this issue : )

**Comment by derberg** [comment]
@aialok please go ahead and open a PR

**Comment by AnshulKahar2729** [comment]
Hey @derberg, I am about to raise a PR for this issue but before that I want to read the guidelines to raise PR, can you help me where can I find out those guidelines?

**Comment by AceTheCreator** [comment]
> Hey @derberg, I am about to raise a PR for this issue but before that I want to read the guidelines to raise PR, can you help me where can I find out those guidelines?

@AnshulKahar2729 do you mean contributors guideline?

**Comment by AnshulKahar2729** [comment]
> > Hey @derberg, I am about to raise a PR for this issue but before that I want to read the guidelines to raise PR, can you help me where can I find out those guidelines?
> 
> @AnshulKahar2729 do you mean contributors guideline? 

Yes

**Comment by AceTheCreator** [comment]
> > > Hey @derberg, I am about to raise a PR for this issue but before that I want to read the guidelines to raise PR, can you help me where can I find out those guidelines?
> > 
> > 
> > @AnshulKahar2729 do you mean contributors guideline?
> 
> Yes

These are the ones I recommend. 
- https://github.com/asyncapi/asyncapi-react/blob/master/CONTRIBUTING.md
- https://github.com/asyncapi/community/blob/master/git-workflow.md

**Comment by AceTheCreator** [comment]
Let me know if you need any help 🙏🏾

**Comment by ajaykumar-br** [comment]
This issue still persists right, can I pick it up?

**Comment by AceTheCreator** [comment]
> @AceTheCreator This issue still persists right, can I pick it up?

Someone opened a PR for it already, sadly. Feel free to pick other existing issues.
