### ISSUE TITLE
Render schemas declared with Remote Reference or URL Reference

### ISSUE THREAD

**Issue by pmgfrederico** [asyncapi/asyncapi-react#1036]
### Description

**Context:** As of today, when declaring a schema through a reference type other than local, the schema is not rendered. The reference, existence of a file or a resource over HTTP, is validated though.

**Feature description:** Render schemas regardless of using Local, Remote or URL reference types by taking into consideration the schemaFormat field.

### Reasons

I am mainly coming from the background of managing AVRO schemas using Schema-Registry and it would be create if one can leverage the $ref construct when Schemas come from an external source of truth other than the AsyncAPI spec.

_I couldn't find the code responsible to do this but I suspect all the building blocks are already in place. Missing parsing an external resource and appending it to the AsyncAPI object model...!?_

**Comment by pmgfrederico** [comment]
Closing issue. I have been mislead by the openapi spec and how to reference components...

**Comment by pmgfrederico** [comment]
Closing issue. I have been mislead by the openapi spec and how to reference components...

**Comment by pmgfrederico** [comment]
Closing issue. I have been mislead by the openapi spec and how to reference components...

**Comment by derberg** [comment]
Hey there, actually we have similar $ref mechanism (of course depends what openapi version are you referring too) and you can even specify Avro and use it directly in AsyncAPI. Just please share your AsyncAPI document and point where the issue is and I'll tell you what might be wrong.

Note though I'm just here today, one day holiday break, and tomorrow going out for few days again, so my reply won't be sooner than next week

**Comment by pmgfrederico** [comment]
> Hey there, actually we have similar $ref mechanism (of course depends what openapi version are you referring too) and you can even specify Avro and use it directly in AsyncAPI. Just please share your AsyncAPI document and point where the issue is and I'll tell you what might be wrong.
> 
> Note though I'm just here today, one day holiday break, and tomorrow going out for few days again, so my reply won't be sooner than next week

First and foremost, thank you for your support. I appreciate it. 

I realized the mistake was on my end. Was mislead from an <anonymous-message-1> MessageID with payload Any. Where actually I did two mistakes:

- using asyncapi: 2.0.0 instead of 3.0.0
- and then referencing a components.schema object instead of a components.messages one...

Got it right here: https://raw.githubusercontent.com/pmgfrederico/pmgfrederico.github.io/master/OrderPlaced.yaml

**Comment by derberg** [comment]
no worries, happy it works for you!
