### ISSUE TITLE
Add an informative stub in case the AsyncAPI document is invalid

### ISSUE THREAD

**Issue by KrySeyt** [asyncapi/asyncapi-react#1048]
**Description**

Hi! I use this component via CDN to generate a schema from json/yaml. Currently, if the AsyncAPI document is invalid, just a blank page is displayed. It would be nice if this component displayed some error information, as in AsyncAPI Studio

CDN version - https://unpkg.com/@asyncapi/react-component@1.0.0-next.54/browser/standalone/index.js

**Reasons**

It will be easier to debug the case when nothing is displayed.

**Comment by Lancetnik** [comment]
I think, it could be related to #874

**Comment by Lancetnik** [comment]
@AceTheCreator can you please tell, which CDN version we can use to get access this feature?
