### ISSUE TITLE
Maintainers update

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi-react#1051]
@magicmatatjahu @fmvilas I wanted to suggest @AceTheCreator as new maintainer and also I wanted to step down.

Ace knows code base very well, did few fixes on his own and also implemented request/reply support

https://github.com/asyncapi/asyncapi-react/commits?author=AceTheCreator

he also knows spec very well, created spec explorer, etc. - I can go on and on

**Comment by fmvilas** [comment]
Absolutely 👍

**Comment by magicmatatjahu** [comment]
👍🏼

**Comment by derberg** [comment]
resolved by https://github.com/asyncapi/asyncapi-react/pull/1073
