### ISSUE TITLE
CodeSandbox example doesn't work

### ISSUE THREAD

**Issue by boskicthebrain** [asyncapi/asyncapi-react#106]
**Description**

CodeSandbox example doesn't work: https://codesandbox.io/s/github/derberg/asyncapi-react-in-action/tree/master/?fontsize=14&file=/src/index.js
![image](https://user-images.githubusercontent.com/6009760/83158209-caa56700-a104-11ea-8636-b07a68fd99f3.png)

**Comment by derberg** [comment]
It is super frustrating as I do not know how to fix it. I tried a few times already, even reported a bug to codesandbox. Funny thing is that once you clone this project to your local and run, all works fine 😞

**Comment by magicmatatjahu** [comment]
@boskicthebrain should work now :)
