### ISSUE TITLE
Cant switch tabs multiple time. It gets stuck on "CONFIGURATION"

### ISSUE THREAD

**Issue by catosaurusrex2003** [asyncapi/asyncapi-react#1069]
**Description**
Current Behaviour
If you go from `SCHEMA` tab to the `CONFIGURATION`, then you cant go back.

**Actual result**

https://github.com/user-attachments/assets/30bba160-742a-458a-bd4f-7d6896c55c8f

**Expected result**

https://github.com/user-attachments/assets/1e8d9ec3-e37a-43f4-ae52-a2abb2926b2b

**Steps to reproduce**
[https://asyncapi.github.io/asyncapi-react/](https://asyncapi.github.io/asyncapi-react/) go here and click on `CONFIGURATION` then you cant go back to `SCHEMA`

**Comment by ItshMoh** [comment]
Hey @catosaurusrex2003 this issue is already been reported. #1008 .

**Comment by catosaurusrex2003** [comment]
My bad. I couldn't find it when i searched for similar issues.
