### ISSUE TITLE
Component Fails to Render:

### ISSUE THREAD

**Issue by milgner** [asyncapi/asyncapi-react#107]
**Description**

Trying to render an incomplete document, the following error and backtrace occur in the console:

```
TypeError: clickedItem is undefined
Toggle.js:27
The above error occurred in the <Toggle> component:
    in Toggle (created by ErrorComponent)
    in section (created by ErrorComponent)
    in ErrorComponent (created by AsyncApiComponent)
    in AsyncApiComponent (at pages/index.tsx:31)
    in div (created by styled.div)
    in styled.div (at pages/index.tsx:30)
    in div (created by styled.div)
    in styled.div (at pages/index.tsx:29)
    in IndexPage (created by HotExportedIndexPage)
    in AppContainer (created by HotExportedIndexPage)
    in HotExportedIndexPage (created by PageRenderer)
    in PageRenderer (at query-result-store.js:86)
    in PageQueryStore (at root.js:56)
    in RouteHandler (at root.js:78)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:69)
    in RouteUpdates (at root.js:68)
    in EnsureResources (at root.js:66)
    in LocationHandler (at root.js:124)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:123)
    in Root (at root.js:132)
    in StaticQueryStore (at root.js:138)
    in _default (at app.js:94)
```

This is a Gatsby-based static rendering app.

**Expected result**

The error component will be rendered.

**Actual result**

See above.

**Steps to reproduce**

 I am not 100% sure about it but it seems to occur during development when trying to render an error about an incomplete YAML definition:

```yml
channels:
  registry:
    subscribe:
      summary: Query information about an object
      operationId: getDeviceInformation
```

**Troubleshooting**

I did not yet investigate further apart from determining that it seems to relate to rendering an error related to an incomplete channel definition.

**Comment by derberg** [comment]
thanks for reporting, please be patient though as we are not fully focused on releasing 1.0 of AsyncAPI parser and generator so we will not have too much time to look into it soon unless @magicmatatjahu you already know what that could be

**Comment by milgner** [comment]
No worries - I first and foremost wanted to capture the report. I should be able to look into it a bit more closely on the weekend, too.
I assume it shouldn't be too hard to narrow down.
