### ISSUE TITLE
SEND/SUB-operations are almost inivisible on sidebar due to missing background color

### ISSUE THREAD

**Issue by FelixPopp** [asyncapi/asyncapi-react#1079]
**Description**
The SEND/SUB-Operation in the sidebar ist not visible due to low contrast between font and background color

**Expected result**
The background-color "bg-blue-600" should be applied
![grafik](https://github.com/user-attachments/assets/3f6dba2e-9ee9-49c9-b3d4-f1f679b7b6dc)

**Actual result**
The background-color is not applied
![grafik](https://github.com/user-attachments/assets/d935dea5-316e-487d-b1f3-cc7129fa8c6a)

Instead "false" is inserted as a CSS-class
![grafik](https://github.com/user-attachments/assets/d9fa6789-5d09-47a0-aec7-3bb9e9fef0e0)

**Steps to reproduce**

1. Open the demo https://asyncapi.github.io/asyncapi-react/
2. Enable the sidebar unter the configuration-tab

**Troubleshooting**
- Propably a follow up bug from #1040 
- Seems like "bg-blue-600" is missing in the bgColors-Array here: 
https://github.com/AceTheCreator/asyncapi-react/blob/master/library/src/containers/Sidebar/Sidebar.tsx#L351

**Comment by Aryan4884** [comment]
@FelixPopp Solved it. Please assign me this issue.
