### ISSUE TITLE
Suggestion to add description on the tooltips of the tags pill

### ISSUE THREAD

**Issue by aditygrg2** [asyncapi/asyncapi-react#1084]
**Description**

Currently if there are any descriptions available on the pill, they are not shown. 

<img width="672" alt="Screenshot 2024-10-14 at 11 05 04" src="https://github.com/user-attachments/assets/b352aa87-deb6-4ca1-a2b1-9ce2f6598983">

Here, external docs have a description, but it is just not shown in visual info. The suggestion is to show the description on the tooltip so when the user hovers over it, it can be shown. 

**Reasons**

Description often contains valuable information about any tags, for example what that pill will take you to, or a better explanation of that tag.

The solution I am thinking of is using a [react-tooltip](https://www.npmjs.com/package/react-tooltip) which can do the work for us.

**Comment by Manancode** [comment]
I've created a PR to address this issue: [#1090](https://github.com/asyncapi/asyncapi-react/pull/1090)
The PR proposes adding tooltip functionality to display descriptions for tags pills. It includes a new TooltipWrapper component, but I failed to locate the external docs information. I will make another PR wrapping the docs with the TooltipWrapper component  It would be really helpful if someone helps me with that @aditygrg2

**Comment by Manancode** [comment]
Sir linked a new [PR](https://github.com/asyncapi/asyncapi-react/pull/1093#issue-2591526622) for it . Please Checkout @catosaurusrex2003

**Comment by AceTheCreator** [comment]
issue resolved by #1093
