### ISSUE TITLE
Support empty payload

### ISSUE THREAD

**Issue by rv0** [asyncapi/asyncapi-react#129]
**Description**

"payload" is not mandatory, therefore it can be empty or just left out completely.
However when you do this, the rendering will fail with an unclear error

Tested on https://playground.asyncapi.io/

**Expected result**

Render empty payload.

**Actual result**

Error (in case of the playground, example is "Cannot read property 'streetlights' of undefined")

**Steps to reproduce**

Remove payload from the a message in the streetlights example.

**Troubleshooting**

We work around it by using an empty object instead in these cases.

**Comment by derberg** [comment]
This component is not used with the generator atm, it's use case is for a client-side apps. It has another preview https://asyncapi.github.io/asyncapi-react/. It doesn't fail when the payload is not provided and shows an empty message, so all good, I tried with:

```

asyncapi: '2.0.0'
id: 'urn:com:smartylighting:streetlights:server'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you to remotely manage the city lights.

    ### Check out its awesome features:

    * Turn a specific streetlight on/off 🌃
    * Dim a specific streetlight 😎
    * Receive real-time information about environmental lighting conditions 📈
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  production:
    url: api.streetlights.smartylighting.com
    protocol: mqtt
    description: Test broker

defaultContentType: application/json

channels:
  test/channel:
    description: The topic on which measured values may be produced and consumed.
    subscribe:
      summary: Receive information about environmental lighting conditions of a particular streetlight.
      operationId: receiveLightMeasurement
      message:
        $ref: '#/components/messages/lightMeasured'

components:
  messages:
    lightMeasured:
      name: lightMeasured
      title: Light measured
      summary: Inform about environmental lighting conditions for a particular streetlight.
```
