### ISSUE TITLE
Rename App component file to Playground

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi-react#144]
**Context**

SonarCloud info:

> By convention, a file that exports only one class, function, or constant should be named for that class, function or constant. Anything else may confuse maintainers.

so let us not confuse ourselves and fix it :smiley:

**Description**

1. Rename [this](https://github.com/asyncapi/asyncapi-react/blob/master/playground/src/App.tsx) file to `Playground.tsx`
2. Rename it also accordingly [here](https://github.com/asyncapi/asyncapi-react/blob/master/playground/src/index.tsx#L4) and [here](https://github.com/asyncapi/asyncapi-react/blob/master/playground/src/index.tsx#L10)﻿

**Comment by magicmatatjahu** [comment]
Solved by https://github.com/asyncapi/asyncapi-react/pull/157
