### ISSUE TITLE
Rename CodeEditor component file to CodeEditorComponent

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi-react#145]
**Context**

SonarCloud info:

> By convention, a file that exports only one class, function, or constant should be named for that class, function or constant. Anything else may confuse maintainers.

so let us not confuse ourselves and fix it :smiley:

**Description**

1. Rename [this](https://github.com/asyncapi/asyncapi-react/blob/master/playground/src/components/CodeEditor.tsx) file to `CodeEditorComponent.tsx`
2. Rename it also accordingly [here](https://github.com/asyncapi/asyncapi-react/blob/master/playground/src/components/index.ts#L2) and [here](https://github.com/asyncapi/asyncapi-react/blob/master/playground/src/App.tsx#L6)﻿

**Comment by sanskar-p** [comment]
@derberg, can I implement this?

**Comment by derberg** [comment]
@sanskar-p sure, please

**Comment by sanskar-p** [comment]
@derberg, what should be the title specification in my PR? I'm guessing it would be either 'chore' or 'refactor'

**Comment by derberg** [comment]
@sanskar-p sorry, my bad. I updated the issue description. Please rename to `CodeEditorComponent`

**Comment by sanskar-p** [comment]
Will do, @derberg

**Comment by sanskar-p** [comment]
@derberg, I came across it in your organization's spreadsheet which was posted in a discord server.

**Comment by derberg** [comment]
@sanskar-p perfect, thanks!
