### ISSUE TITLE
Make playground available as a separate npm package

### ISSUE THREAD

**Issue by kaibra** [asyncapi/asyncapi-react#146]
**Description**
This repository provides two nice tools: a react-component to visualize asynapi-specs and a playground for writing async-api specs in an editor and see the results visualized.
The playground is currently only maintained for local development as far as I understand and can't be accessed apart from cloning this repository.
https://github.com/asyncapi/playground is a server-side version of the playground ?!

I suggest to publish the "playground" of this repository (could be renamed to asyapi-editor) as (at least) a react-component as well, since I think it is a nice tool which can be useful for others.

To increase accessibility of the package, it would be worth to think about providing a dependecy free bundle also (like: https://www.npmjs.com/package/swagger-editor-dist). 

As already mentioned in 

https://github.com/asyncapi/asyncapi-react/pull/76
https://github.com/asyncapi/asyncapi-react/pull/75

Regards, 

Kai

**Reasons**
This feature would make another tool available in the asyncapi space, which is already there, but inaccessible.
It would be similar to https://www.npmjs.com/package/swagger-editor
I think developers coming from OpenAPI would appreciate to find such a tool.

**Attachments**
*none*

**Comment by derberg** [comment]
The current AsyncAPI Playground is here https://playground.asyncapi.io/
Playground for this react component is published here https://asyncapi.github.io/asyncapi-react/

Or you say someone would prefer to use react playground locally instead of the official one?

**Comment by kaibra** [comment]
Yes, exactly. People could embed it in their own applications for example.

**Comment by sebastian-palma** [comment]
I might second this. I'm currently trying to wrap different documentation tools into a single application (Rails 6) and I think the playground would be a good addition.

By now I think I can dig through the .ts files in the playground and make it work but that would leave me behind master/main changes.

**Comment by derberg** [comment]
still valid, we just need some help from the community

**Comment by SimonAlling** [comment]
Second that. Same use-case here. Could even be part of the `@asyncapi/react-component` package, as far as I'm concerned.

**Comment by bidadh** [comment]
I also need editor in my angular application

**Comment by derberg** [comment]
FYI, I know that @magicmatatjahu is working on it atm. Actually, he is building a new editor/playground from scratch :)

**Comment by magicmatatjahu** [comment]
@derberg it was supposed to be a surprise 😅

**Comment by derberg** [comment]
🤷🏼

**Comment by derberg** [comment]
related https://github.com/asyncapi/asyncapi-react/issues/273

**Comment by derberg** [comment]
@kaibra Hey, playground is just internal integration tool for react component development. We will not push it to npm. 

Instead, we have https://github.com/asyncapi/studio/ that we push out to npm regularly. Can you have a look if there is something more we need to do to make the studio more usable as a dependency?
