### ISSUE TITLE
What is the recommended way to consume this component?

### ISSUE THREAD

**Issue by scottohara** [asyncapi/asyncapi-react#160]
When consuming the component, I encountered a number of errors trying to build with webpack; and the resulting bundle size for my `vendor` bundle ended up at 4Mb (3.24Mb of this is `webapi-parser`).

Clearly I'm doing something wrong?

Here's how I did it:

1. Install the dependencies:
```
npm i @kyma-project/asyncapi-react react react-dom
```

2. Consume the component:
```ts
// app.tsx
import React from "react";
import { render } from "react-dom";
import AsyncApi, { ConfigInterface } from "@kyma-project/asyncapi-react";

const config: Partial<ConfigInterface> = {
  show: {
    schemas: false
  },
  showErrors: false
};

const schema = ` (omitted for brevity) `;

render(<AsyncApi schema={schema} config={config} />, document.getElementById("root"));
```

3. Build with webpack (`mode=production`)

The first build error I encountered was:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'node_modules/webapi-parser'
```

...which I was able to suppress by adding the following to my `webpack.config.js`:

```js
node: {
  fs: "empty"
},
```

The next error I encountered was:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'ajv/lib/refs/json-schema-v5.json' in 'node_modules/json-schema-migrate/lib'
```

It would seem that `json-schema-migrate` needs `ajv@5.x`; but one of the webpack plugins I use (`mini-css-extract-plugin`) needs `ajv@6.x` (which doesn't include the file `json-schema-v5.json`.

In my case, npm installed `ajv@5.x` in the `node_modules` folder inside `json-schema-migrate`, so I was able to suppress this error with a webpack alias:

```js
resolve: {
  alias: {
    "ajv/lib/refs/json-schema-v5.json": "json-schema-migrate/node_modules/ajv/lib/refs/json-schema-v5.json"
  },
```

Similarly, `markdown-it` requires the file `entities/maps/entities.json`, but the file path (on my machine) is actually `entities/lib/maps/entities.json`, so another webpack alias fixes that:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'entities/maps/entities.json' in 'node_modules/markdown-it/lib/common'
```

```js
resolve: {
  alias: {
    "ajv/lib/refs/json-schema-v5.json": "json-schema-migrate/node_modules/ajv/lib/refs/json-schema-v5.json",
    "entities/maps/entities.json": "entities/lib/maps/entities.json"
  },
```

With those errors fixed, I'm able to build successfully, but the size of the bundle is huge.

Here's what it looks like in `source-map-explorer`:

![vendor-9dafdf_js_-_Source_Map_Explorer](https://user-images.githubusercontent.com/289327/95037792-e4406600-0717-11eb-9dfc-167bd0b5c8c9.png)

Is this expected?

**Comment by derberg** [comment]
@scottohara good catch, afaik it is caused by `@asyncapi/raml-dt-schema-parser` that should not be even a part of this component as it is not browser compatible. I think we just need to remove it and all things will be back to normal. @fmvilas any objections?

**Comment by magicmatatjahu** [comment]
We should also think about removing other parsers for openapi and avro and document that avro and openapi has compability in browser and if someone want to use it, then must add it manually, but raml isn't supported.

**Comment by magicmatatjahu** [comment]
@scottohara As I know, some people and organisations use our component by using CRA (https://github.com/facebook/create-react-app) also with latest (in time when I write comment) `0.13.1` version and no one has reported any bugs (I'm not saying there aren't). Do you want use this component in other lib/framework than React? I'm asking because I think that if you installing component with react, and react-dom, you want to use the component alongside an existing application. Am I correct?

**Comment by scottohara** [comment]
Hi @magicmatatjahu,

Yes we are looking to use the component in a React app, but one that was not generated using CRA.

If others have had success using the component in CRA-based apps, perhaps that suggests we have a problem with our `webpack.config.js` that ends up bringing in more of the `asyncapi-react` source than is needed?

**Comment by scottohara** [comment]
For what it's worth, the [playground demo](https://asyncapi.github.io/asyncapi-react/) also has a large 4.7Mb chunk (which compresses to 1.1Mb with Gzip):

![image](https://user-images.githubusercontent.com/289327/95151760-37c5b900-07d7-11eb-9e81-af12b451790d.png)

**Comment by derberg** [comment]
if we remove `@asyncapi/raml-dt-schema-parser` then the bundle will get significantly smaller as it is using `https://github.com/raml-org/ramldt2jsonschema` that has `webapi-parser` that is super large https://bundlephobia.com/result?p=webapi-parser@0.5.0

**Comment by magicmatatjahu** [comment]
I removed custom schema parsers and unused/unnecessary code in this https://github.com/asyncapi/asyncapi-react/pull/163 and here is a output from `source-map-explorer` of builded plauground with changes in component:

![image](https://user-images.githubusercontent.com/20404945/95264170-2d370e00-082f-11eb-9545-84cc77ade220.png)

With react-dom, react and deps in library it's about 400kb, rest are deps for playground.

**Comment by derberg** [comment]
@magicmatatjahu you removed a bit too much :D

**Comment by magicmatatjahu** [comment]
@scottohara Thanks very much for this issue, because bundle is critical for browser app. Your another problems with webpack must fix by aliases (as you wrote, it is caused by the webpack plugins which you use). I hope that we merge fix as quick as possible.

@derberg I updated PR :)

**Comment by derberg** [comment]
@magicmatatjahu stop putting pressure on me 😛
