### ISSUE TITLE
Address XSS vulnerability in dompurify by updating dependency

### ISSUE THREAD

**Issue by renvrant** [asyncapi/asyncapi-react#168]
This issue will be resolved by merging https://github.com/asyncapi/asyncapi-react/pull/135

**Comment by magicmatatjahu** [comment]
@renvrant Hello :) I created a PR with grouped bump of deps with security issues here https://github.com/asyncapi/asyncapi-react/pull/169 Could you wait until tomorrow before the second codeowner (@derberg) does the review?
