### ISSUE TITLE
Websocket Subprotocol Support

### ISSUE THREAD

**Issue by gexclaude** [asyncapi/asyncapi-react#174]
**Description**

In one of our applications, we use STOMP over WebSockets. As we want to make use of AsyncAPI in order to document this API we stumbled upon the lack of "subprotocol" support.

What is the "subprotocol" regarding WebSockets? A WebSocket connection is simply a connection. It can be used to tunnel almost anything, starting with things like plain text messages but also video streaming or database connections. See [IANA WebSocket Protocol for Subprotocols](https://www.iana.org/assignments/websocket/websocket.xml)

AsyncAPI allows setting a server protocol and protocol version. The protocol may be ws|wss for WebSocket or stomp|stomps for STOMP (https://www.asyncapi.com/docs/specifications/2.0.0#serverObject). A combination is not possible yet.

For WebSockets, it would be good to have a `subprotocol` field which would contain the WebSocket subprotocol identifier. For STOMP 1.2 this would be `v12.stomp` (according to IANA WebSocket Protocol Registries). A separation of `subprotocol` and `subprotocolVersion` could be an alternative, but I think it would not help.

**Reasons**

Without any way to document protocol tunneling, I assume it is not possible to describe APIs using STOMP over WebSockets using AsyncAPI in a standardized manner. I would need to choose between either `ws` or `stomp` as protocol and describe in plain text that the other protocol is involved too.

**Comment by gexclaude** [comment]
wrong repository!

**Comment by derberg** [comment]
@gexclaude if you did not create a new one yet, I can transfer it for you to the right repo, lemme know
