### ISSUE TITLE
Fixed RefreshIcon location

### ISSUE THREAD

**Issue by confuser** [asyncapi/asyncapi-react#200]
**Description**
Set the refresh icon (on https://asyncapi.github.io/asyncapi-react/) to a fixed location so it's still visible when scrolling through YAML content on left hand pane.

**Reasons**
When debugging a large AsyncAPI document (few hundred lines+), manually scrolling to the top of the page each time to trigger an update is somewhat tedious. Having the refresh icon in a fixed location that's always visible regardless of scrolling would avoid this.

**Comment by derberg** [comment]
@confuser don't you think that the best would be to not have a refresh button at all, so rendering works real-time and not only on button click?

**Comment by magicmatatjahu** [comment]
As I remember we had real-time rendering, but then the rendering was too frequent and the DX dropped in case of large schemes, but we can try to delay it, e.g. 2 seconds from the last schema update.

**Comment by derberg** [comment]
@magicmatatjahu I don't recall. In official playground it works pretty well and nobody complained so far

**Comment by magicmatatjahu** [comment]
@derberg I added PR with delay and fixed refresh icon 😸
