### ISSUE TITLE
show `const` values in property description

### ISSUE THREAD

**Issue by c-pius** [asyncapi/asyncapi-react#210]
**Description**

If a property has a `const` value assigned, the const value is not shown as part of the rendered property description (it is shown as the value in `examples` though).  Swagger editor does for instance show `const` values.

**Expected result**

`const` value should be shown in the property description.

**Actual result**

`const` value is omitted from the property description.

**Steps to reproduce**

Add the following property to an arbitrary payload.

```json
"cityName": {
    "type": "string",
    "const": "Ratisbona"
}
```

**Troubleshooting**

I assume the `const` value would already be part of the parsed schema, so would adding the const to the SchemaPropertiesComponent would be sufficient?
https://github.com/asyncapi/asyncapi-react/blob/36d3a21dabedb0e8c74876b7626f9a8045901ea3/library/src/containers/Schemas/SchemaProperties.tsx#L174

Swagger editor:
![image](https://user-images.githubusercontent.com/22994291/102019145-0555b080-3d72-11eb-8e15-ff5e91d0c6b8.png)

AsyncApi react component
![image](https://user-images.githubusercontent.com/22994291/102019150-0e468200-3d72-11eb-997c-e66e2333cf2b.png)

**Comment by derberg** [comment]
@c-pius we are not removing anything from schema after parsing it (just adding stuff) so as you wrote, it is just a matter of adding proper support in the component
