### ISSUE TITLE
Intagrate Lerna changelog

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/asyncapi-react#22]
**Description**

At this moment, we do not have a changelog for two releases: `0.1.0` and `0.1.1` and in addition, we do not have labels for the library and playground app and for other areas, so we must integrate lerna changelog with our repo for providing more information for releases.

AC:
- add new labels for library, playground, documentation, community etc.
- integrate Lerna changelog with out package.

**Reasons**

For providing more information for releases.

**Attachments**

[Lerna changelog](https://github.com/lerna/lerna-changelog)

**Comment by derberg** [comment]
Do 0.2 release in case of new styles set as default because of https://github.com/asyncapi/asyncapi-react/issues/25. 
Don't worry about old releases, focus on the new one and future, to have proper configuration and readme for future
