### ISSUE TITLE
React component does not work when exported from node_modules/@asyncapi/web-component/lib/asyncapi-web-component.js

### ISSUE THREAD

**Issue by rols2015** [asyncapi/asyncapi-react#231]
**Description**
I am trying to use react component in my nodeJs (ejs) application.
```html 
<script src="<%= rootPath %>/vendors/asyncapi/web-component/lib/asyncapi-web-component.js"></script>
<script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
```

```javascript
ReactDOM.render(
            React.createElement(AsyncApiWebComponent, {
                      schema,
                    }
            ),
            document.getElementById('swagger-ui')
    );
```

![image](https://user-images.githubusercontent.com/16349586/105414488-8e7bc500-5c05-11eb-8488-b01d397d97b4.png)

Am I missing something?
I am mostly back-end developer and do not have much experience with react.
Any suggestions would be appreciated.

Thank you so much

**Comment by derberg** [comment]
@rols2015 I'm curious why you have to use the Web Component instead of directly the React component?
Web component is rather for non-React apps, unless you use Next.js 

Have you seen this example https://codesandbox.io/s/asyncapi-react-component-in-action-wvdy2 from readme?

**Comment by rols2015** [comment]
Thanks @derberg yes, I tried it as well. and get another error:

![image](https://user-images.githubusercontent.com/16349586/105422170-48c4f980-5c11-11eb-9ba3-193e43ce5685.png)


![image](https://user-images.githubusercontent.com/16349586/105422151-3f3b9180-5c11-11eb-8404-fb41b9c63f08.png)

**Comment by rols2015** [comment]
@derberg actually I was able to manage it by rendering schema in the fly.
Everything is fine now except error in console. 
![image](https://user-images.githubusercontent.com/16349586/105430452-8b8ecd80-5c21-11eb-90df-2602ff4f2c9d.png)

**Comment by derberg** [comment]
@rols2015 `in the fly` you mean on page load? or? This is how it should work at the end. For something static better use HTML template.

Hard to say why you're getting error without seeing the code. the `url` property is part of `schema` props. You use it when you want to point to an AsyncAPI file stored on a remote server. I have to see the code to say more really. Can you put something maybe on CodeSandbox or just directly to GitHub?

**Comment by rols2015** [comment]
thank you for your response @derberg 
yes, on page load. I have something like this where inputs variable is shema (json object). Not sure how can I render it using remote `url`.
```javascript
    function createfn(){
      var element = document.createElement("asyncapi-component");
      element.setAttribute('style', 'width: 100%');
      element.setAttribute('cssImportPath', '<%= rootPath %>/vendors/asyncapi/react-component/lib/styles/fiori.css');
      element.setAttribute('schema', <%- JSON.stringify(inputs) %>);
      document.getElementById('swagger-ui').appendChild(element);

    }
```

**Comment by rols2015** [comment]
I also tried and I see the same error (it's not rendered at all)
```javascript
      element.setAttribute('schemaUrl', 'https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/streetlights.yml');
      element.setAttribute('schemaFetchOptions', '{"method":"GET","mode":"cors"}');
```

**Comment by magicmatatjahu** [comment]
@rols2015 Hi! Could you try something like:

```html
<head>
  <!-- Remove 'webcomponentsjs' if no support for older browsers is required -->
  <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.5.0/webcomponents-bundle.js"></script>
  <script src="https://unpkg.com/@asyncapi/web-component@0.19.0/lib/asyncapi-web-component.js" defer></script>
  <script>
    var schema = JSON.stringify(JSON.parse(inputs));
    window.onload = function() {
      document.getElementById("asyncapi").schema=schema;
    };
  </script>
</head>
<body>
  <asyncapi-component
    id="asyncapi"
    cssImportPath="https://unpkg.com/@asyncapi/react-component@0.19.0/lib/styles/fiori.css">
  </asyncapi-component
</body>
```

Your first problem `Could not convert AsyncAPI file to JSON` is related (as error said) with your JSON. You can see in console tab that your json after `stringify` has a newlines and by this you cannot render it. If example above won't work, please go to your first solution and parse correctly JSON using `parse`, `stringify` or `json.replace(/\\n/g, '')` in some combinations. Let me know if it worked :)

**Comment by rols2015** [comment]
@magicmatatjahu thank you. I tried your code yeterday with no luck. I found a better solution using `schema.url`
The below code works fine for me, however when I tried `schemaUrl` it was ignored.
The problem related with empty url was related that code was executed before url was specified. (`defer` attribute)
```javascript
    function renderAsyncApi(){
      var element = document.createElement("asyncapi-component");
      element.setAttribute('style', 'width: 100%');
      element.setAttribute('cssImportPath', '<%= rootPath %>/vendors/asyncapi/react-component/lib/styles/fiori.css');
      element.setAttribute('schema', '{"url":"https://myhost.images/c8389094-3b6b-4862-b7f8-76acffc08bef.json"}');
      element.setAttribute('schemaFetchOptions', '{"method":"GET","mode":"cors"}');
      document.getElementById('swagger-ui').appendChild(element);
    }
```

**Comment by magicmatatjahu** [comment]
@rols2015 great!

> The below code works fine for me, however when I tried schemaUrl it was ignored.

`schemaUrl` is added today in this commit https://github.com/asyncapi/asyncapi-react/commit/aa0a6da813dc45d0d8c400d104895b7c3a5e3040 If you could, try `schemaUrl` with version 0.19.0 of our component :)

**Comment by rols2015** [comment]
@magicmatatjahu thank you so much. `schemaUrl` works like a charm with ` "@asyncapi/web-component": "^0.19.0"`
Thanks again @derberg @magicmatatjahu and have a great weekend :)

**Comment by derberg** [comment]
@aeworxet look, already the first fan of `schemaUrl` 🥳

**Comment by aeworxet** [comment]
I am extremely glad that `schemaUrl` is in demand among people. :grin:

**Comment by rols2015** [comment]
Hello guys, one more question: @aeworxet @derberg @magicmatatjahu 
when I use `schemaUrl` it sends a few requests to the same resource
![image](https://user-images.githubusercontent.com/16349586/105893231-d5403500-5fe0-11eb-9398-f3ea1ac7d5a0.png)

**Comment by rols2015** [comment]
Also when I use my own api to get asyncAPI json the following message is shown until I get a response.
![image](https://user-images.githubusercontent.com/16349586/105905292-4509ec00-5ff0-11eb-94a8-8af433361ed6.png)
Can the `asyncapi-component` be rendered once url/json is parsed?

**Comment by derberg** [comment]
@rols2015 strange 🤔 it is not the fault of the parser for sure as I checked it and parser performs just one request (we use parser here that has fetching functionality). 

I also tested quickly the react component directly with https://codesandbox.io/s/asyncapi-react-component-in-action-wvdy2 sandbox and I also saw just one request.

So looks like only web-component is causing some problems here. We surely need to investigate. @rols2015 could you open up a separate issue please

**Comment by rols2015** [comment]
sure, thanks
