### ISSUE TITLE
Broken Link Listed In Constants File & Displayed To User

### ISSUE THREAD

**Issue by SteveSonoa** [asyncapi/asyncapi-react#249]
**Description**

/lib/constants.d.ts includes the following code on line 3 (as of v0.19.1):
`export declare const CONTENT_TYPES_SITE = "https://www.iana.org/assignments/media-types";`
This is a broken link. It displays when the following yaml is used:
`asyncapi: 2.0.0
info:
  title: "Streams SSE Subscription for topic 'salesforce-leads-change'"
  version: 1.0.0
  description: >
    This Streams SSE Subscription allows you to receive events published to the
    Streams Topic 'salesforce-leads-change'.
servers:
  sse:
    url: "http://localhost"
    protocol: http
defaultContentType: text/event-stream
channels:
  '/subscribers/sse/topics/salesforce-leads-change':
    description: The root path on which any published events on Streams will be sent
    subscribe:
      operationId: publishRecord
      message:
        oneOf:
          - $ref: '#/components/messages/snapshotMessage'
          - $ref: '#/components/messages/patchMessage'
components:
  messages:
    snapshotMessage:
      name: streams-snapshot-message
      title: Streams Snapshot Message
      contentType: application/json
      traits:
        - $ref: '#/components/messageTraits/commonHeaders'
      payload:
        $ref: '#/components/schemas/recordPayload'
    patchMessage:
      name: streams-patch-message
      title: Streams Patch Message
      contentType: application/json
      traits:
        - $ref: '#/components/messageTraits/commonHeaders'
      payload:
        $ref: '#/components/schemas/jsonPatchOperations'
  messageTraits:
    commonHeaders:
      headers:
        type: object
        properties:
          id:
            type: string
            description: Unique identifier of the event
          event:
            type: string
            description: Type of the event
  schemas:
    jsonPatchOperations:
      type: array
      items:
        type: object
        properties:
          op:
            type: string
            enum:
              - add
              - remove
              - replace
              - move
          path:
            type: string
          value:
            type: string
        required:
          - op
          - path
      example: >-
        data: [{ "op": "replace", "path": "/baz", "value": "boo" }, { "op":
        "add", "path": "/hello", "value": ["world"] }, { "op": "remove", "path":
        "/foo" }]
    recordPayload:
      $schema: "http://json-schema.org/draft-07/schema"
      $id: "sfdc-event-schema"
      type: "object"
      title: "The schema of SFDC LeadChangeEvent"
      required:
       - "Status"
       - "LastModifiedDate"
       - "ChangeEventHeader"
      properties:
        Status:
          $id: "#/properties/Status"
          type: "string"
        LastModifiedDate:
          $id: "#/properties/LastModifiedDate"
          type: "string"
        ChangeEventHeader:
          $id: "#/properties/ChangeEventHeader"
          type: "object"
          title: "The ChangeEventHeader content"
          required:
           - "commitNumber"
           - "commitUser"
           - "sequenceNumber"
           - "entityName"
           - "changeType"
           - "changedFields"
           - "changeOrigin"
           - "transactionKey"
           - "commitTimestamp"
           - "recordIds"
          properties:
            commitNumber:
              $id: "#/properties/ChangeEventHeader/properties/commitNumber"
              type: "integer"
              title: "The commitNumber schema"
            commitUser:
              $id: "#/properties/ChangeEventHeader/properties/commitUser"
              type: "string"
              title: "The commitUser schema"
            sequenceNumber:
              $id: "#/properties/ChangeEventHeader/properties/sequenceNumber"
              type: "integer"
              title: "The sequenceNumber schema"
            entityName:
              $id: "#/properties/ChangeEventHeader/properties/entityName"
              type: "string"
              title: "The entityName schema"
            changeType:
              type: "string"
              title: "The changeType schema"
            changedFields:
              type: "array"
              title: "The changedFields schema"
              items:
                type: "string"
            changeOrigin:
              $id: "#/properties/ChangeEventHeader/properties/changeOrigin"
              type: "string"
              title: "The changeOrigin schema"
            transactionKey:
              $id: "#/properties/ChangeEventHeader/properties/transactionKey"
              type: "string"
              title: "The transactionKey schema"
            commitTimestamp:
              $id: "#/properties/ChangeEventHeader/properties/commitTimestamp"
              type: "integer"
              title: "The commitTimestamp schema"
            recordIds:
              $id: "#/properties/ChangeEventHeader/properties/recordIds"
              type: "array"
              title: "The recordIds schema"
              items:
                type: "string"
`

Tested in Firefox & Chrome on Mac & Windows.

**Expected result**

If an external link is present from our site, it should not be a broken link. Ideally, we should have the option of disabling a link. I'm not sure what this link is used for.

**Actual result**

A new tab opens showing a 404 on the iana.org website.

**Steps to reproduce**

Begin a React project with v0.19.1. Return <AsyncApiComponent> with the spec={yaml_from_above} />

**Troubleshooting**

It's a broken link. We've visited the site in error.

**Comment by derberg** [comment]
@SteveSonoa hey, can you please provide a formatted YAML document that I can easily copy/paste, or its JSON version? Thanks in advance 🙏🏼

**Comment by magicmatatjahu** [comment]
@SteveSonoa Hi! This is not a broken link - it shows details of your `defaultContentType`. For example if your schema will has `defaultContentType` set to `application/json` then you will have https://www.iana.org/assignments/media-types/application/json In your schema you have `text/event-stream` value, and it's probably a broken content-type. Component shouldn't check that content-type is valid or not.

**Comment by SteveSonoa** [comment]
> @SteveSonoa Hi! This is not a broken link - it shows details of your `defaultContentType`. For example if your schema will has `defaultContentType` set to `application/json` then you will have https://www.iana.org/assignments/media-types/application/json In your schema you have `text/event-stream` value, and it's probably a broken content-type. Component shouldn't check that content-type is valid or not.

Thank you for the clarification! I'll consider the issue resolved and look at our usage instead.
