### ISSUE TITLE
Removing theme in the playground breaks application 

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi-react#25]
**Description**

At the moment the Playground looks unstable because of:
- the `theme` option errors
- the changes in schema that are breaking yaml or are invalid with spec are not really reflected in the playground after hitting refresh button. There is no indicator in UI, just info in the console

Overall improvements:
- Fixes in library or playground related to this bug should have unit tests
- If new version needs to be released it should contain change log and should be properly marked in the github release section

**Expected result**

- application still works and default style is applied to the component
- errors in the UI are visible, best, realtime without refreshing
- maybe we should have even a separate switcher button for switching between themes
- maybe the custom style that is by default a part of the playground should become a default one (default style is what we see in official editor http://editor.asyncapi.org/)? What do you think @fmvilas ? should we maintain the default style as it is? or use only the one that is in the playground? I think that having both, styles implemented in the component and changeable with some prop is probably not a good idea as it will only increase the size of the component.

**Actual result**

white page with errors in browser console

**Steps to reproduce**

go to https://www.asyncapi.com/asyncapi-react/ and clear the custom theme and hit refresh

**Comment by fmvilas** [comment]
I think we should have a default style, whatever it is. Let's not worry too much if it's exactly the same (or not) as the one at editor.asyncapi.org. What do you think?

\cc @rmelian

**Comment by derberg** [comment]
If having style the same as editor.asyncapi.org is not mandatory I prefer to go with the one that we have in the playground as default and forget about the one in editor.asyncapi.org. to ease the maintenance.

**Comment by fmvilas** [comment]
How can I see the default style? I mean, the playground default one.

**Comment by derberg** [comment]
because of the bug in the Playground you can go to the sandbox project https://codesandbox.io/s/5vz8l9zlmn and get the default but not passing the `theme={theme} ` prop to the component. It looks the same as in the original AsyncApi editor, and I suggest the default is what you get after passing the prop

**Comment by fmvilas** [comment]
Oh! I see. In my opinion, the default should be your theme, but it would be nice to provide the current default as a theme. Probably in a different directory of the project or in a different repo.

**Comment by fmvilas** [comment]
:shipit:

**Comment by derberg** [comment]
https://www.npmjs.com/package/@kyma-project/asyncapi-react 0.2.0 is out

**Comment by fmvilas** [comment]
Great stuff folks! 👏
