### ISSUE TITLE
Playground doesn't show names of schemas referenced by oneOf 

### ISSUE THREAD

**Issue by strobe** [asyncapi/asyncapi-react#252]
If the schema of the message using a 'oneOf' then the Playground displays oneOf items only with indexes names like 0,1,2 etc 
but seems it should also display names of references schemas too (and non react version of Playground has that)  

See this example in https://asyncapi.github.io/asyncapi-react/ 

```yaml
asyncapi: 2.0.0
info:
  title: oneOf example 
  version: 1.0.0-alpha
servers:
  dev:
    url: localhost:8080
    protocol: ws
channels:
  /stream:
    description: the stream 
    subscribe:
      operationId: onStream
      summary: stream of states info
      message:
        $ref: '#/components/messages/ResponseState'
    bindings:
      ws:
        method: GET
components:
  schemas:
    ResponseState:
      description: possible states of backend
      oneOf:
        - $ref: '#/components/schemas/SomeTypeName01'
        - $ref: '#/components/schemas/SomeTypeName02'
        - $ref: '#/components/schemas/SomeTypeName03'
    SomeTypeName01:
      type: object
    SomeTypeName02:
      type: object
    SomeTypeName03:
      type: object  
  messages:
    ResponseState:
      payload:
        $ref: '#/components/schemas/ResponseState'
      contentType: application/json
 
```

I'm expecting to see names like: 'SomeTypeName01', 'SomeTypeName02', 'SomeTypeName03' near indexes.

This is similar to https://github.com/asyncapi/asyncapi-react/pull/156 .
That PR solves that for messages but the same happens with schemas too.

**Comment by derberg** [comment]
@strobe thanks for the issue, your request makes a lot of sense. Is it something you were thinking to contribute?
