### ISSUE TITLE
ExpandAll button doesn't works for 'oneOf' schemas.

### ISSUE THREAD

**Issue by strobe** [asyncapi/asyncapi-react#253]
The 'ExpandAll' playground button doesn't expand 'oneOf' schemas.
 
for example, in this case, it's leaves 'SomeTypeName01', 'SomeTypeName03', 'SomeTypeName03' collapsed.

```yaml
asyncapi: 2.0.0
info:
  title: oneOf example 
  version: 1.0.0-alpha
servers:
  dev:
    url: localhost:8080
    protocol: ws
channels:
  /stream:
    description: the stream 
    subscribe:
      operationId: onStream
      summary: stream of states info
      message:
        $ref: '#/components/messages/ResponseState'
    bindings:
      ws:
        method: GET
components:
  schemas:
    ResponseState:
      description: possible states of backend
      oneOf:
        - $ref: '#/components/schemas/SomeTypeName01'
        - $ref: '#/components/schemas/SomeTypeName02'
        - $ref: '#/components/schemas/SomeTypeName03'
    SomeTypeName01:
      type: object
    SomeTypeName02:
      type: object
    SomeTypeName03:
      type: object  
  messages:
    ResponseState:
      payload:
        $ref: '#/components/schemas/ResponseState'
      contentType: application/json
```

So as a result of you have three like data structures with many levels is not possible to do an overview of documentation easially.

**Comment by derberg** [comment]
@magicmatatjahu any suggestions mate? where to look at for the issue? where is the logic responsible for expand/collapse of all.

**Comment by magicmatatjahu** [comment]
@strobe Hi! Sorry for late response. I passed your schema in our playground and every schema in `Schemas` section expanded. Do you mean that message's schemas for `/stream ` channel aren't expanded, like in picture below?

![image](https://user-images.githubusercontent.com/20404945/109306393-68b69100-783f-11eb-838c-c17d9b3b7948.png)

**Comment by magicmatatjahu** [comment]
@derberg Logic is related with internal component state, here https://github.com/asyncapi/asyncapi-react/blob/master/library/src/store/useExpandedState.ts We use ids for each element to expand/collapse and probably we don't add ids to nested oneOf/anyOf/allOf schemas

**Comment by magicmatatjahu** [comment]
Due to the fact that in the newer version of the component (on next branch) we don't have expand button, I close issue. It will be reopened if necessary.
