### ISSUE TITLE
Add the ability to change the size of the split panes 

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/asyncapi-react#268]
**Description**

**This is related to the playground**. Add the ability to resize the split panes(the vertical line in the middle).

**Reasons**

Right now the editor window is kind of small, so the ability to resize it will give the power to users to resize it as they desire.

**Attachments**

To make it more clear, this vertical line(separation) is what I'm talking about:
![vertical line](https://user-images.githubusercontent.com/54525741/111876797-65d63880-89c6-11eb-9a38-ea1ca0d27a01.png)

If the maintainers approve this feature request, I might be able to work on it.

**Comment by magicmatatjahu** [comment]
@aayushmau5 Hi! If you want, feel free to make PR for this :)

**Comment by aayushmau5** [comment]
Thanks.
