### ISSUE TITLE
Connect Netlify to our repository

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/asyncapi-react#306]
**Description**

At the moment we host our playground in the Github Pages. If we go with Netlify hosting we can test and see changes from PR from Netlify temporary site for PR. I don't know if there is a possibility to connect this repo to Netlify account used by [website](https://www.asyncapi.com/). Someone must check it.

**Reasons**

To Improve DX in PR's review.

**Comment by aayushmau5** [comment]
I will check if it can be done.

**Comment by aayushmau5** [comment]
Just checked. Yeah, Netlify supports multiple repos from the same account.

**Comment by magicmatatjahu** [comment]
@aayushmau5 Thanks for checking it! :)

**Comment by fmvilas** [comment]
Do we want to keep this playground? I mean, we already have AsyncAPI Studio. I'd focus all efforts in this direction.

**Comment by magicmatatjahu** [comment]
@fmvilas Right, but we have requests to publish to npm playground (or only editor part like in Studio) in [this issue](https://github.com/asyncapi/asyncapi-react/issues/146) and [here](https://github.com/asyncapi/asyncapi-react/issues/273). We can copy this editor from studio (which is better, because under the hood we use monaco-editor, not codemirror) and have `@asyncapi/editor` which will be used in studio and as standalone. What do you think? Of course code for this editor will be where currently is `playground` in this repo.

Swagger has also editor published as standalone component https://github.com/swagger-api/swagger-editor and for me this is a good approach.

**Comment by magicmatatjahu** [comment]
It's not necessary at this time. If there is a need, I will open issue again.
