### ISSUE TITLE
Rewrite components to stateless components and use React hooks

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/asyncapi-react#36]
**Description**

At the moment library and playground app have in the vast majority stateful components (created by class). In `16.8.0` version of React, the hooks feature will be made available. 

AC:
- rewrite components to stateless components,
- if component has a state, please add state functionality by using React hooks.

**Reasons**

Willingness to improve speed of rendering and more readable code.

**Attachements**
- [React hooks overview](https://reactjs.org/docs/hooks-intro.html)

**Comment by derberg** [comment]
@all-contributors please add magicmatatjahu for code, doc, ideas, maintenance,

**Comment by derberg** [comment]
@all-contributors please add kazydek for doc, review, maintenance, please add akucharska for code, maintenance and please add derberg for doc, examples, ideas

**Comment by derberg** [comment]
@all-contributors please add kazydek for doc, review, maintenance

**Comment by derberg** [comment]
@all-contributors please add akucharska for code, maintenance

**Comment by derberg** [comment]
@all-contributors please add derberg for doc, examples, ideas

**Comment by derberg** [comment]
@all-contributors please add akucharska for code, maintenance

**Comment by derberg** [comment]
@all-contributors please add akucharska for code, maintenance

**Comment by derberg** [comment]
@all-contributors please add derberg for doc, examples, ideas

**Comment by derberg** [comment]
sorry for spamming the issue :(

**Comment by jakebolam** [comment]
Multi user add coming soon! https://github.com/all-contributors/all-contributors-bot/issues/100

**Comment by aerfio** [comment]
@all-contributors please add aerfio for code, doc, ideas, maintenance, review, tests

**Comment by magicmatatjahu** [comment]
@all-contributors please add magicmatatjahu for code, doc, ideas, maintenance, review, tests
