### ISSUE TITLE
Add to all TailwindCSS classes the prefix

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/asyncapi-react#369]
**Description**

In the next version of component we use the TailwindCSS for styling. We don't use the prefixes for TailwindCSS classes used inside the component. It can ends with duplicated classes with other properties than ours in some application - in other words, users can attach to application existing TailwindCSS stylings based on "normal" TailwindCSS class names, so they can override our styles or our styles can override other.

This approach is used in several project like stoplight (they use the `sl` prefix) etc.

We should use the `prefix` options for TailwindCSS https://tailwindcss.com/docs/configuration#prefix but the question is, what prefix? `ai` as a shortcut of `asyncapi` or maybe another?

**Comment by fmvilas** [comment]
I don't really see what's the problem of using the regular TailwindCSS classes. Mind explaining a bit better?

**Comment by magicmatatjahu** [comment]
@fmvilas

> in other words, users can attach to application existing TailwindCSS stylings based on "normal" TailwindCSS class names, so they can override our styles or our styles can override other.

Also in TailwindCSS docs for `prefix`:

> The prefix option allows you to add a custom prefix to all of Tailwind’s generated utility classes. This can be really useful when layering Tailwind on top of existing CSS where there might be naming conflicts

People can have in application own styles based on custom TailwindCSS config, other that us, and it could ends with overriding the styles in their app, or in our component.

**Comment by fmvilas** [comment]
I see. Thanks for explaining!

As a prefix, it's common to see people using `a2s` as **A**sync**A**pi **S**pecification. Another suggestion would be `arc` as in **A**syncapi **R**eact **C**omponent.

**Comment by magicmatatjahu** [comment]
No problem, I very like the `a2s` :) Thanks!

**Comment by derberg** [comment]
`arc` seems better as related to the component itself

**Comment by derberg** [comment]
yeah, forgot about this `ui` idea. Then `aui` 😉

**Comment by magicmatatjahu** [comment]
Fixed by https://github.com/asyncapi/asyncapi-react/pull/493
