### ISSUE TITLE
Create script to generate the custom theme

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/asyncapi-react#370]
**Description**

We use the TailwindCSS for styling the component in the `next` version fo component. TailwindCSS is based on the config file in which we can change the base value for some css properties like color, bg-color etc. By this we can create script which will generate the whole styles as new theme based on used TailwindCSS classes inside the source code of component.

Some AC:
- script should have high DX - dev should write the TailwindCSS config and only pass the path of custom config to script
- script should be written in the package in the `tools` or `scripts` folder
- great would be if dev wouldn't have to install local dev dependencies to run the script. Needed deps like `postcss`, `tailwindcss` should be shipped in package as `dependencies` or should be `install` after first run of the script - the second option is better
- custom config and the default defined in package should me merged, with more priority of custom
- script should produces the production styles with and without the the css normalizer from TailwindCSS - https://github.com/asyncapi/asyncapi-react/issues/368

NICE TO HAVE:
- custom plugins for TailwindCSS and PostCSS should also work in script. It means that if someone pass custom plugin in `plugins` array in the TailwindCSS then script should work with it - it's worth highlighting as in some cases we may have a problem with dependencies and `node_modules`

Then this script can be used in our https://github.com/asyncapi/cli

Any other ideas? Feel free to comment!

**Comment by ritik307** [comment]
@magicmatatjahu can you provide me with some resources regarding making scripts as mentioned above.
