### ISSUE TITLE
oneOf, anyOf & allOf not working when used as array item

### ISSUE THREAD

**Issue by fujiapple852** [asyncapi/asyncapi-react#377]
**Description**

The use of either `oneOf`, `anyOf` or `allOf` as the `items` of an `array` renders the message as `Array<Unknown>` and cannot be expanded.  

For example, the following schema (valid JSON Schema Draft 07):

```json
{
  "type": "array",
  "items": {
    "oneOf": [
      {
        "type": "boolean"
      },
      {
        "type": "integer"
      }
    ]
  }
}
```

Is rendered as follows:

<img width="540" alt="Screenshot 2021-06-18 at 9 54 21 AM" src="https://user-images.githubusercontent.com/36075719/122495958-8a6d9b00-d01d-11eb-9c0c-fb9e8336a4e6.png">

Note that the `Examples` section works as expected, and generates examples messages that match the schema: 

<img width="414" alt="Screenshot 2021-06-18 at 9 54 30 AM" src="https://user-images.githubusercontent.com/36075719/122495966-8e012200-d01d-11eb-9210-1c52b4ecb55f.png">

**Expected result**

If we wrap the `oneOf`, `anyOf` or `allOf` inside a dummy `object` then they are rendered correctly, for example, the following schema:

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "dummy": {
        "oneOf": [
          {
            "type": "boolean"
          },
          {
            "type": "integer"
          }
        ]
      }
    }
  }
}
```

Is rendered correctly:

<img width="509" alt="Screenshot 2021-06-18 at 9 58 40 AM" src="https://user-images.githubusercontent.com/36075719/122495978-93f70300-d01d-11eb-9a35-825a0c1d2965.png">

**Actual result**

As shown in the description.

**Steps to reproduce**

The following minimal complete asyncAPI example demonstrates the issue:

```json
{
  "asyncapi": "2.0.0",
  "info": {
    "title": "Test",
    "version": "1.0.0",
    "description": "Test anyOf/oneOf/allOf in array"
  },
  "channels": {
    "myChannel": {
      "subscribe": {
        "message": {
          "name": "myMessage",
          "payload": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "integer"
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

**Comment by fujiapple852** [comment]
There is a (partial) workaround for cases where the array is guaranteed to have at least one element:

```json
{
  "type": "array",
  "items": [{
    "oneOf": [
      {
        "type": "boolean"
      },
      {
        "type": "integer"
      }
    ]
  }],
  "additionalItems": {
    "oneOf": [
      {
        "type": "boolean"
      },
      {
        "type": "integer"
      }
    ]
  }
}
```

This renders as:

<img width="527" alt="Screenshot 2021-06-18 at 10 30 51 AM" src="https://user-images.githubusercontent.com/36075719/122497637-492aba80-d020-11eb-9564-7412633d00ef.png">

Whilst this still shows `Array<Unknown>` it can at least be expanded.

Note that later revisions of the JSON Schema specification have revised validation logic for `items` and `additionalItems` (and `prefixItems`) and so the above may only be valid for JSON Schema Draft 07 (the version used by asyncapi 2.0.0)

**Comment by magicmatatjahu** [comment]
@fujiapple852 Thanks for raised the issue and for awesome description with examples!. I will try fix this problem in https://github.com/asyncapi/asyncapi-react/pull/367 PR.

**Comment by magicmatatjahu** [comment]
@fujiapple852 Tuple types will be showed as:

![image](https://user-images.githubusercontent.com/20404945/122553266-be55ba00-d037-11eb-89c2-6e8dfb3b53eb.png)

but oneOf in array will be showed as:

![image](https://user-images.githubusercontent.com/20404945/122553331-d4fc1100-d037-11eb-9b5e-952366961bb7.png)

Do you have any insights?

Can I ask you something? Do you use the `next` version of component as standalone component or you use the `@asyncapi/html-template`?

**Comment by magicmatatjahu** [comment]
Fixed in `@asyncapi/react-component@1.0.0-next.9`. @fujiapple852 If you will have any another problems, please create issue or reopen it (of course if it will be related to type rendering).

**Comment by fujiapple852** [comment]
Thank you very much @magicmatatjahu!  The rendered versions look good, can you show the json/yaml that produced these for reference?

> Do you use the next version of component as standalone component or you use the @asyncapi/html-template?

I have been using the `@asyncapi/html-template` and also the playground.  Is it possible to use `next` version from the `ag` tool?

**Comment by magicmatatjahu** [comment]
Thanks!

> ...can you show the json/yaml that produced these for reference?

Yeah, sure, here they are:

Tuple

```json
{
  "type": "array",
  "items": [
     {
       "oneOf": [
          { "type": "boolean" },
          { "type": "integer" }
       ]
     }
  ],
  "additionalItems": {
       "oneOf": [
          { "type": "boolean" },
          { "type": "integer" }
       ]
  }
}
```

Array:

```json
{
  "type": "array",
  "items": {
    "oneOf": [
      { "type": "boolean" },
      { "type": "integer" }
    ]
  }
}
```
