### ISSUE TITLE
Navigation in asyncapi-component in angular

### ISSUE THREAD

**Issue by dominik3131** [asyncapi/asyncapi-react#386]
**Description**

Using `asyncapi-component` in angular renders schema in `shadowRoot`, which turns off navigation to sections by `a` tags and ids. This can be easily repaired by listening to mouse clicks events in `shadowRoot` and filtering mouse events to ones that are done on `a` tags and then scrolling manually to proper elements. However bigger problem exist when page is accessed with hash in url like for example `https://asyncapi.github.io/asyncapi-react/#message-lightMeasured`. Because there is no way of knowing if schema was already fully rendered, i have to delay scroll to element placed in url hash by some time to allow it to render. But this isn't best solution as this makes user wait for a bit for scroll and also this can possibly be buggy when render takes too much time.

**Possible solution**
Get rid of shadowRoot to allow native browser navigation or add event to  `asyncapi-component` indicating that rendering of schema completed.

**Comment by magicmatatjahu** [comment]
@dominik3131 Hi! 

Do you use the `@asyncapi/react-component` as web-component with `@asyncapi/web-component` package, or use the `next` version of component?  If this first, could you try to use the AsyncAPI Standalone bundle with this https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/angular.md doc? Remember about installing component as:

```bash
npm install --save @asyncapi/react-component@next
```

**Comment by dominik3131** [comment]
@magicmatatjahu Hi!

I have tried `AsyncAPI Standalone` and it works better, render is faster and there is no `shadowRoot`. However i noticed that i will need to scroll manually anyway because our API docs are huge and it can take long time to finish GET request. Due to this fact native scroll to hash from URL won't work anyway. So solution to my problem would only be some kind of event when schema render is done.  Is it possible to add?

**Comment by magicmatatjahu** [comment]
@dominik3131 I make this trick to postpone the first scrolling to the element from hash:

```ts
    fetch(...) // URL for your schema
      .then(res => res.json())
      .then(spec => {
        AsyncApiStandalone.render({ schema: spec }, container);
        setTimeout(() => {
          const hash = window.location.hash;
          const node = this.element.nativeElement.querySelector(`#${CSS.escape(hash.substring(1))}`) as HTMLDivElement;
          node.scrollIntoView();
        }, 0);
      });
```

You will start rendering the component after fetching the spec. Callback used in `setTimeout` will be

**Comment by dominik3131** [comment]
@magicmatatjahu that's actually really similar to my solution. Guess i will stick to it :-) We just prefer in our projects solutions that avoid all kinds of timeouts if possible. Thanks :-) I will close this issue.

**Comment by magicmatatjahu** [comment]
@dominik3131 So I guess it works for you, am I right? If you will have a problems with timeouts, please reopen the issue :) And regarding to your thoughts about timeouts: I also don't like this approach, but we don't want to add any additional props/callbacks to our component, rather that we want to focus on some generic way to link to internal state of component, not exactly like this https://github.com/asyncapi/asyncapi-react/issues/305 but very similar - we must rethinking the idea of hooks. Something like in SwaggerUI with custom plugins where you can use the internal component's state.

**Comment by dominik3131** [comment]
@magicmatatjahu Yeah this works for me. I just wanted solution that is more bug proof in the future. Anyway, thanks again.
