### ISSUE TITLE
Bad indentation for properties and objects description on generated doc via AsyncAPI Playground

### ISSUE THREAD

**Issue by tmdoit** [asyncapi/asyncapi-react#393]
**Description**

Issue is related to description text for properties and objects. I see that the cause of the problem could be with description text length, descriptions with the same text length has the same indentation.  Additionally text seems to be aligned to the right.
![Zrzut ekranu 2021-07-13 o 17 39 00](https://user-images.githubusercontent.com/85706044/125482187-66fe2cfb-642c-40d9-8b90-cd4f1ec298e3.png)

OS: MacOS Big Sur 11.2.3
Browser: Wersja 1.26.74 Chromium: 91.0.4472.124 (Oficjalna wersja) (arm64)

**Expected result**
Regularity in description presentation.

**Actual result**
No regularity in description presentation.

**Steps to reproduce**
Attached files imported from AsyncAPI Playground.
[asyncapi (3).zip](https://github.com/asyncapi/asyncapi-react/files/6810289/asyncapi.3.zip)

**Comment by magicmatatjahu** [comment]
@BOLT04 Hi! I remember trying to do it on shrink, but some things didn't look right, and it looked worse than it does now. You can try again if you want :)

**Comment by magicmatatjahu** [comment]
Fixed in the `next-29` https://github.com/asyncapi/asyncapi-react/pull/509#issuecomment-1011148252
