### ISSUE TITLE
The web component doesn't support the config attribute?

### ISSUE THREAD

**Issue by jonsage** [asyncapi/asyncapi-react#394]
The web component doesn't appear to support the config attribute in any way.

**Comment by magicmatatjahu** [comment]
@jonsage Hi! Did you use the `webcomponent` from master or from [next branch](https://github.com/asyncapi/asyncapi-react/tree/next) (installed as `@asyncapi/web-component@next`)?

Please also add more information in which environment - framework are you using the component.

**Comment by jonsage** [comment]
Hi, I've tried both master and next, I'm not using the component in any framework, just HTML.

The scripts load from unpkg as in the examples.

I've tried config as an attribute, and also as a property (accessing the webcomponent node through JS).

I've taken a look in the webcomponent tsx file, and the config property isn't exported but it is registered when defining the custom element.

I can find no usage example of using config with the web component so this might just be something I'm doing wrong - right now I've tried passing in a JSON object as the value:

```
config='{ "show": { "sidebar": true } }'
```

**Comment by magicmatatjahu** [comment]
For me this html works:

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/@asyncapi/web-component@0.24.3/lib/asyncapi-web-component.js" defer></script>
  </head>
  <body>

    <asyncapi-component
      schemaUrl="https://raw.githubusercontent.com/asyncapi/spec/v2.0.0/examples/2.0.0/streetlights.yml"
      schemaFetchOptions='{"method":"GET","mode":"cors"}'
      config='{"show": {"info": false}}'
      cssImportPath="https://unpkg.com/@asyncapi/react-component@0.24.3/lib/styles/fiori.css">
    </asyncapi-component>

  </body>
</html>
```

So I pass config as stringified JSON as in your example.

**Comment by jonsage** [comment]
I have this, but it wont show the sidebar :/

```
<asyncapi-component
  schemaUrl="https://raw.githubusercontent.com/asyncapi/spec/v2.0.0/examples/2.0.0/streetlights.yml"
  schemaFetchOptions='{"method":"GET","mode":"cors"}'
  cssImportPath="https://unpkg.com/@asyncapi/react-component@0.24.0/lib/styles/fiori.css"
  config='{"show": {"sidebar": true}}'>
</asyncapi-component>
```

**Comment by magicmatatjahu** [comment]
Sidebar is added in the `next` version in component :)

Try this:

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/@asyncapi/web-component@1.0.0-next.12/lib/asyncapi-web-component.js" defer></script>
  </head>
  <body>

    <asyncapi-component
      schemaUrl="https://raw.githubusercontent.com/asyncapi/spec/v2.0.0/examples/2.0.0/streetlights.yml"
      schemaFetchOptions='{"method":"GET","mode":"cors"}'
      config='{"show": {"sidebar": true }}'
      cssImportPath="https://unpkg.com/@asyncapi/react-component@1.0.0-next.12/styles/default.min.css">
    </asyncapi-component>

  </body>
</html>
```

**Comment by magicmatatjahu** [comment]
You can also use the standalone bundle - preferrer way, because web-component has shadow dom, which breaks the `hashchange` event and style must be imported as `cssImportPath` prop - due to shadow CSS...

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://unpkg.com/@asyncapi/react-component@1.0.0-next.12/styles/default.min.css">
  </head>
  <body>
    
    <div id="asyncapi"></div>

    <script src="https://unpkg.com/@asyncapi/react-component@1.0.0-next.12/browser/standalone/index.js"></script>
    <script>
      AsyncApiStandalone.render({
        schema: {
          url: 'https://raw.githubusercontent.com/asyncapi/spec/v2.0.0/examples/2.0.0/streetlights.yml',
          options: { method: "GET", mode: "cors" },
        },
        config: {
          show: {
            sidebar: true,
          }
        },
      }, document.getElementById('asyncapi'));
    </script>

  </body>
</html>
```

I will update the docs :)

**Comment by jonsage** [comment]
One problem with the approach above is the default.css (without shadow DOM) leaks Tailwind global CSS affecting typography amongst other things - it would be good if all the styles included were scoped to just the component and not the rest of the site hosting it.

I'm not knowledgeable on React and Tailwind so I'm not sure the best way to do this, but I thought I'd just bring it to your attention in case you felt it was worth looking into :)

Thank you so much for your time and effort btw - it's extremely appreciated.

**Comment by magicmatatjahu** [comment]
If you have in mind normalizer/reset CSS from TailwindCSS, we know about that and we have issue for that https://github.com/asyncapi/asyncapi-react/issues/368 and PR is on the way :)

**Comment by magicmatatjahu** [comment]
Docs will be merged with PR https://github.com/asyncapi/asyncapi-react/pull/395

**Comment by jonsage** [comment]
@magicmatatjahu 
> … because web-component has shadow dom, which breaks the `hashchange` event

Is there a plan to capture the click and scroll to the target element instead of relying on the `hashchange`? It seems like a big caveat to have the sidebar not work to navigate. That way the shadow dom issue wouldn't matter.

**Comment by magicmatatjahu** [comment]
It's a solution, but we don't want to add "extra" logic inside component. It should only render the html. We have something similar in the master branch:

![image](https://user-images.githubusercontent.com/20404945/126174896-caad58ae-907f-493a-98af-8ed32d740818.png)

and it's a buggy, really buggy. Probably in the future we will remove the `web-component` and only support the standalone bundle, due to fact that we want to add plugins feature https://github.com/asyncapi/asyncapi-react/issues/305 and the web-component doesn't support passing functions (as ref) as prop to itself.

BTW. I merged the https://github.com/asyncapi/asyncapi-react/pull/395 PR with docs how to pass the config to web-component. 

If you will have another problems, please open another issue, or reopen it. I will close it, thanks for informing us about this issue :)
