### ISSUE TITLE
Display protocol on bindings in capsule instead of drop down

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/asyncapi-react#414]
The idea is to improve the actual bindings UI to match the initial implementation do in the html-template

**Reasons**

- improve the user experience when reading bindings blocks
- gain one level on rendering (because the protocol part is attached to the bindings title) into the bindings parts

**Attachments**

Here is the previous rendering (available on html-template 0.20) on the left side and the actual rendering on the right side

![image](https://user-images.githubusercontent.com/5501911/129580629-bc51f6ac-eddb-443b-9a51-094923db3554.png)

**Comment by magicmatatjahu** [comment]
I changed the way of rendering the bindings to have consistent with extensions also with other parts of messages/operations like `payload` etc. In 99% cases developer will define single binding for given parts of spec, so rendering the name of binding in the root level makes sense.

**Comment by magicmatatjahu** [comment]
@M3lkior I created PR with "old look". If you have any concerns, please write them as the comment under PR https://github.com/asyncapi/asyncapi-react/pull/416 :)

**Comment by magicmatatjahu** [comment]
Merged in ` 1.0.0-next.18` version
