### ISSUE TITLE
Standalone JSON Schema renderer component

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/asyncapi-react#426]
Currently we have own JSON Schema React component for rendering the JSON Schema. It's hardcoded inside component, but we should split it to the separate npm package - and then also reuse it inside React component.

Additionally, we need it for such a issue:
https://github.com/asyncapi/extensions-catalog/issues/43

It will be also very helpful for people that need JSON Schema renderer in their custom components (https://github.com/asyncapi/asyncapi-react/issues/279#issuecomment-831356194).

**Comment by Fox32** [comment]
Would look forward to see such a component!

**Comment by jonaslagoni** [comment]
Would love to see this as well!

**Comment by AceTheCreator** [comment]
@magicmatatjahu any luck if i can work on this issue if it's still open?

**Comment by magicmatatjahu** [comment]
@AceTheCreator Hi! The task is difficult because we probably have to separate this component from the package. We want to do the same with other components and have a library of components and not just one component, so for now this task is "on hold".

**Comment by jonaslagoni** [comment]
> @AceTheCreator Hi! The task is difficult because we probably have to separate this component from the package. We want to do the same with other components and have a library of components and not just one component, so for now this task is "on hold".

Will it not be possible for you to describe the tasks that are needed to accomplish this? 🤔
