### ISSUE TITLE
Add other documentation engines and move playground to its own repo

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi-react#44]
**Description**

As we've discussed before, the playground in this project will become the editor for version 2.0.0. I'm already working on it and it's time to start adding HTML and Markdown engines, as well as code generation too very soon.

I was hacking the playground here but feels like we probably should be moving it to the https://github.com/asyncapi/editor repo and leave this repo just for the React component.

**Reasons**

Release cycles of the playground will have nothing to do with the React component alone anymore as we'll have more documentation engines and features not related to the React component.

What do you think?

**Comment by derberg** [comment]
I totally agree. If the playground is going to be an official editor, then it must be split from the react component

**Comment by fmvilas** [comment]
In the meantime I created a new playground. Check it out: https://asyncapi-playground.herokuapp.com/.

I did a component architecture using Handlebars and static rendering so it's easier to migrate.

The repo is github.com/asyncapi/playground.

**Comment by derberg** [comment]
it is on heroku because of serverside nature?

**Comment by fmvilas** [comment]
Yes. editor.asyncapi.org is also server-side and it's on Digital Ocean. This instance on Heroku is just for testing, we'll move it over to editor.asyncapi.org once it's finished.
