### ISSUE TITLE
Ability to auto-expand message schema

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi-react#440]
## Description

If one has a scheme that is too large and deep, then the component will render a very large amount of nesting that one has to manually click through to see the deep schema values. To increase the UX, we should have an additional button next to subschema button - a button to show deep nesting.

## Solution

The changes should be introduced in the [Schema component](https://github.com/asyncapi/asyncapi-react/blob/next/library/src/components/Schema.tsx). If the user presses the extra button, all subschemas should open/close (depending if subschemas are opened/closed).

---

> **NOTE**: Below is old description

@davydog187 commented on [Wed Jan 22 2020](https://github.com/asyncapi/generator/issues/202)

Hello and thank you for this great project!

## The Problem
I have nested payload structures that are 3-4 levels deep, and it is cumbersome to keep clicking to view the schema. 

## Potential Solution
It would be nice if there was an option in the generator that has nested structures auto-expanded, maybe with a parameter to specify the level of nesting that you want to stop auto-expanding. 

I could be interested in helping contribute, but would need some pointing in the right direction :) Thanks!

---

@fmvilas commented on [Wed Feb 05 2020](https://github.com/asyncapi/generator/issues/202#issuecomment-582338627)

Hey @davydog187. Thanks for the suggestion. It would indeed be great. Any help would be much appreciated 🙏

**Comment by magicmatatjahu** [comment]
Still valid. PR is opened for that issue https://github.com/asyncapi/asyncapi-react/pull/514

**Comment by fmvilas** [comment]
Closing as it seems the bot failed to do it.
