### ISSUE TITLE
Set the left menu collapsable

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/asyncapi-react#441]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?

Depending on the screen resolution, the menu on the right side overlay the spec content
- How will this change help?
Allow the user to collapse this menu if needed
- What is the motivation? 
A degraded user experience

![image (13)](https://user-images.githubusercontent.com/5501911/119680927-e9d2f380-be41-11eb-8a31-c0bddffb8ed4.png)

#### Description
Please try answering few of those questions
- What changes have to be introduced?
A new button to collapse the menu with a new collapsed style (a vertical layout to allow the expand ?)
- Will this be a breaking change?
no
- How could it be implemented/designed?

A vertical layout with a collapse / expand icon

![image](https://user-images.githubusercontent.com/5501911/119682433-2c490000-be43-11eb-94ce-6f077630b168.png)

**Comment by Krishks369** [comment]
Is this issue still active? if yes can you please once more elaborate the issue. I would like to contribute in it.

**Comment by M3lkior** [comment]
Hello @Krishks369 ; i think yes it is about the ui enhancement :)

**Comment by Krishks369** [comment]
I don't find any menu in right side of the UI
![image](https://user-images.githubusercontent.com/71367204/142233420-48258fa7-f3b7-4865-bb7b-e362c1210cbe.png)

Please correct me if I am Wrong, i am a complete beginner

**Comment by M3lkior** [comment]
how do you obatin this screeshot ? if you use the html-template generation you will see the menu; if you look at this thread https://github.com/asyncapi/asyncapi-react/issues/441#issuecomment-849545750, there is a menu on the right side showing the `operations` name, the `tags`, the `components`, etc;

**Comment by magicmatatjahu** [comment]
@Krishks369 Hi! If you are still willing to contribute, you need to make changes on the branch next, in the file https://github.com/asyncapi/asyncapi-react/blob/next/library/src/containers/Sidebar/Sidebar.tsx :
- add some state where you will save expanded/collapsed state of menu
- make it consistent with other styling
So you need to fork repo, switch to next branch and on it make changes. If you will need help, please ping me in this thread :) Every info, how to setup dev environment etc is in [Readme.md](https://github.com/asyncapi/asyncapi-react/tree/next)

**Comment by sambhavgupta0705** [comment]
Hey @magicmatatjahu can I work on this issue?

**Comment by Asrk03** [comment]
hey @M3lkior  @magicmatatjahu  can you assign me this issue?

**Comment by magicmatatjahu** [comment]
@sambhavgupta0705 Sure, you can reuse code from https://github.com/asyncapi/asyncapi-react/pull/624

**Comment by sambhavgupta0705** [comment]
hey @magicmatatjahu 
I am having problem while setting up this repo locally
These are the errors:
![image](https://user-images.githubusercontent.com/81870866/229838426-03f812cc-95b9-453f-8564-35918ec742dd.png)
