### ISSUE TITLE
Which AsyncAPI versions are supported?

### ISSUE THREAD

**Issue by leonheess** [asyncapi/asyncapi-react#456]
I expected the latest release to support all available AsyncAPI versions. However, this is not the case. Are the supported versions listed somewhere and is there maybe a roadmap telling me when support for the newer versions will drop?

**Comment by derberg** [comment]
@leonheess hey, we support all from 2.0.0 up. I think you did not notice info that was at the top of the readme

> ⚠️ We are in the process of rewriting the component under the next branch. The current version 0.X.X is in the maintenance mode, we are focusing mainly on the next branch. Check out releases with next suffix in the release tag or the next tag on NPM.

I'm pretty sure `next` releases support all AsyncAPI 2.x versions. Does it help?

**Comment by derberg** [comment]
@leonheess you can freely use `next` branch and related release candidates, they are constantly deployed and battle-tested on our https://playground.asyncapi.io/. @magicmatatjahu it might make sense to push latest release there 😉 

but regarding readme on master, if you say it is not clear, I say we need to make it even more clearer, as community is the boss here. @leonheess best would be if you could open a PR with change suggestion. Let us know if you are keen to do it

> Is there a timeline on when master will support the new content?

The goal is that once `next` goes into `master` we release a first 1.0.0 release. To make sure we can do it @magicmatatjahu is now working on a new playground -> https://github.com/asyncapi/studio/ to make sure it is really production-ready and not breaking changes need to be introduced. @magicmatatjahu correct me if I'm wrong but I think that once studio is released and replaces playground, we release 1.0 of react component?
