### ISSUE TITLE
Upgrade marked dependency

### ISSUE THREAD

**Issue by arjangeertsema** [asyncapi/asyncapi-react#521]
**Description**

[The library](https://github.com/asyncapi/asyncapi-react/blob/v1.0.0-next.30/library/package.json) uses a very old [marked dependency](https://www.npmjs.com/package/marked/v/2.1.1) which has a [high vulnerability](https://github.com/advisories/GHSA-5v2h-r2cx-5xgj).

Please upgrade to the [patched version](https://www.npmjs.com/package/marked/v/4.0.10).

**Comment by magicmatatjahu** [comment]
Handled by https://github.com/asyncapi/asyncapi-react/pull/522
