### ISSUE TITLE
feat: config option to expand/collapse the examples payload

### ISSUE THREAD

**Issue by thim81** [asyncapi/asyncapi-react#532]
**Description**

There are a number of configuration options, it would be nice if you could configure the default expand/collapse behaviour for the "Examples" section.

**Reasons**

As a visitor of the AsyncAPI documentation, you want to see the details of the message properties and having a the example visibile next to message properties, makes it easier to correlate the content of the value with an actual example value.

**Attachments**

![2022-01-26 at 11 25 00](https://user-images.githubusercontent.com/952446/151146496-cb3619b5-53cc-433a-acb2-6bc0223c8d8b.png)

**Comment by magicmatatjahu** [comment]
@thim81 Hi! If we go with that direction I think that we should have also option to expand `payload` and `headers` on the left (to be consistent).

**Comment by thim81** [comment]
Agreed, that would be another feature request depending on this request.

**Comment by magicmatatjahu** [comment]
Resolved by https://github.com/asyncapi/asyncapi-react/pull/621
