### ISSUE TITLE
the pattern field is displayed as lowercase that is not appropriate for pattern like [A-Z]{3}

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/asyncapi-react#549]
**Description**

the display of the pattern field is lower cased that is it not appropriate when using a regex like `[A-Z]{3}` that is displayed as  `[a-z]{3}`

**Expected result**

Display the pattern like it is set in the specification

![image](https://user-images.githubusercontent.com/5501911/154302814-59a96101-1843-46c4-b343-2b6b590d89e5.png)

**Actual result**

![image](https://user-images.githubusercontent.com/5501911/154298383-3c80ed93-92ee-4d55-ad13-f1c0f4b77984.png)

**Steps to reproduce**

Start from the AsyncAPI studio and add the ` "pattern": "[A-Z]{3}"` in any field to see the rendering

**Troubleshooting**

To solve the issue, simply remove the `lowercase` css class in the https://github.com/asyncapi/asyncapi-react/blob/next/library/src/components/Schema.tsx (line 170)

**Comment by magicmatatjahu** [comment]
Fixed by https://github.com/asyncapi/asyncapi-react/pull/550
