### ISSUE TITLE
Unhandled Rejection (SyntaxError) when no Servers defined

### ISSUE THREAD

**Issue by rmelian** [asyncapi/asyncapi-react#57]
**Description**

when there is no defined servers section the parser breaks with the exception:

![image](https://user-images.githubusercontent.com/4565267/63873150-11efa300-c98d-11e9-9f81-801c287b83ed.png)

**Expected result**
as servers section is not required it should render correctly 

**Actual result**

**Steps to reproduce**

Any document with NO servers section

**Troubleshooting**

**Comment by rmelian** [comment]
I just tested with last @magicmatatjahu  PR https://github.com/asyncapi/asyncapi-react/pull/58 and is working fine there

**Comment by aerfio** [comment]
As #58 is merged can we close this?
