### ISSUE TITLE
User Research: Survey to understand main problems potential users are currently facing

### ISSUE THREAD

**Issue by mcturco** [asyncapi/asyncapi-react#593]
I am proposing that we create a survey and share it with community members and engineers/architects in the EDA space and see what kind of foundational feedback we can get to provide a focus problem as we improve the UX of the AsyncAPI react component (Something that I think we should re-name, perhaps to: **AsyncAPI Docs UI**, open to suggestions)

## ❓  **Why do we need this foundational research?**
I have been tasked with making the documentation components "better" as currently it is arguably a bit visually inconsistent and rather confusing depending on the complexity of the AsyncAPI file the UI is documenting. However, that is merely a hypothesis, and it more or less addresses the visual style, which is more of a UI problem (we are going to definitely make that better). In order to make improvements on the user experience side of things, we need to ask some basic questions to get a sense of the pain points that our users might be facing currently. This could be a user whom is already using AsyncAPI, or potential users that are questioning whether it might be a good idea to use AsyncAPI to define and document their EDA. 

I think that a brief set of questions can help us establish some of these problems at a higher level, and give us a "jumping off point" to start brainstorming ideas on how we might be able to solve those problems. A quick way to receive feedback from a number of different individuals is by sending out an online survey which directly asks the users how they are feeling currently. We can do this easily with [Google Forms](https://www.google.com/forms/about/), which has worked well for us in the past.

## ✏️  **Survey questions**
Here are some survey questions that I have come up with that I think can give us some more information at a basic level. I am still learning about software dev and EDAs, so if there is some wording in there that doesn't make sense please let me know! If you think we should add/subtract questions, I would love to hear your feedback 😄 

`/* Who are our end users? */`
- Are you a developer/architect/engineer on a team working to document an event-driven architecture/microservice(s)? Are you a developer/architect/engineer who builds applications within an existing event-driven architecture/microservice? Both? If the answer is other, please elaborate.

`/* What problems are our end users facing? */`

- How are you currently documenting your event-driven architecture?
- What challenges do you face while documenting your event-driven architecture? How does it make you feel?
- Is there any way in which you feel these challenges can be resolved?
- What tools/processes are you and/or your team currently using to know which events are available to you as a developer? 
- What challenges do you face when using you and/or your team's EDA documentation to know what steps you need to take to build your integration?
- Is there any way in which you feel these challenges could be resolved?

## 🤔  **How will we ask for participation?**
My plan is that we share the link to the survey from official AsyncAPI social accounts and contributors on their own can reshare those posts for traction if they would like to spread the word for visibility.

## ⌛  **How long should we keep the survey open for?**
I don't want this to drag out too long, but I think it is important for the quality of the responses to have the survey open for enough time where we can be sure that everyone within the community and beyond has seen posts about it at least more than once in case the first time they saw a post about it they did not have enough time to complete it. I would say a good amount of time would be 3 weeks.

## 📈  **How will the results be shared?**
Once the survey time period has closed, I will sort all of the responses in a digestible way and post them in this issue. From there, we can begin discussing what problem space we should focus on, and then brainstorm designs on how we might be able to solve that problem.

**Comment by akshatnema** [comment]
**Can we extend the idea of this survey such that it uses the website also to take opinions and answers to the question asked in the survey?**

The reason why I proposed this is because most of our end users (whether they are working on documenting EDA or working on applications using EDA) will be using our website for the documentation. An end user who is using AsyncAPI in his application must have gone through the AsyncAPI docs or maybe he repeatedly read it for more information related to Spec. In this way, we can get the views of the majority end users using the website, instead of circulating Google forms through our social media handles. To be clear, I'm not against the idea of Google Form, but to make the survey more open and reachable to the public, my thinking goes more in the direction of using website in making the survey.

**Comment by mcturco** [comment]
Hey @akshatnema 😄 
Good idea, I definitely think we can promote the survey on the docs somehow, perhaps in a way that is non-intrusive to the user reading the docs to understand AsyncAPI. However, this survey may reach potential users whom have never used AsyncAPI before but do use EDA in their day to day programming. I think it is important to keep the survey topic more focused on understanding the challenges that EDA users face, not only AsyncAPI users. The reason I suggest using Google Forms is because the platform makes it easy to keep responses public, something that is important in our community. But I definitely think we can have a link on the website to promote the survey, but we should also be promoting on social to reach more users outside of the AsyncAPI org 😄

**Comment by akshatnema** [comment]
@mcturco Fine then, if the survey is needed to reach the potential users who are not aware of EDA till now, we can then not restrict the survey form to the website anyway. It's better if it gets shared on social media. Secondly, your idea to attach the Google form link in our website is the good and clear one. Nothing complicated design is not required there :wink:. A fine approach that I can think of is to make a pop-up box in the website that display after a certain time interval, if the visitor remains on the website. It can easily be implemented since we are using `next/router`. The working of the window can be like this - After around 5-10 mins of a visitor presence on the website, we can show a popup dialog which will ask the visitor to fill up the survey form, whose link will be given in the box. 

Regarding the User Research and Survey questions you presented, I completely satisfied with the questions and the motive behind. But I think, @fmvilas @alequetzalli and @derberg are best persons in the organization to help you out with this :slightly_smiling_face:.

**Comment by derberg** [comment]
the best way to share the google form would be to do it in the studio, the place where we get regular, returning visitors. Some kind of banner or something could be displayed. Social media is not so effective in such cases, asyncapi.com too IMHO. Best is always to ask for feedback direct daily users inside the app they use

**Comment by derberg** [comment]
@mcturco 

> Which of the following areas best describes your current position

I would add `Software Architecture` to the list

> Email

if someone doesn't want to be contacted, do they need to provide email? I think there are many people not super happy sharing email through google tools, so might be better to ask for email at the end of the form, only those that want to be contacted for more details. Anyway, just a hint

**Comment by mcturco** [comment]
# ✅  Survey complete
Hey everyone, just closed the survey as I felt like it has been open for some time and we were able to get a bunch of decent responses out of it. I have spent some time organizing the responses a bit so we can better analyze where our users' pain points lie, and this might help us to know what we should be working on next for docs tooling.

## Download spreadsheet of responses
Here is a spreadsheet of the 24 responses from this survey in a Google Sheets doc --> https://docs.google.com/spreadsheets/d/1CChN9uV6gZHx3d2f9l3qxRDFxgKqWEBcSNqCk_bzOy4/edit?usp=sharing

## Summary
I feel that the qualitative data from this survey was more useful than the quantitative data, so please note that I will be reporting on those findings more specifically. 

### Summary of current tools used for documentation
- Confluence
- Git Wiki
- Google Docs
- Markdown
- Mermaid.js
- Notion
- Whimsical
- Libraries
- APIOps
- EventCatalogue
- IcePanel
- Stoplight
- Docusaurus
- draw.io
- Devs look at the code or ask other devs

![Image](https://user-images.githubusercontent.com/60163079/178051492-ed8d8408-b904-49fe-9e54-f19599e60874.png)


### Summary of challenges 
- Difficulty with documentation versioning/updates
- Lack of tooling around API documentation
- Trouble keeping documentation in sync with code
- Lack of detail and examples in a lot of docs
- Documentation is written after implementation, but it should be generated from a specification
- Most people don’t want to write specs
- Sharing events through libraries is not ideal for documentation
- Challenges with sharing events
- Challenges with storing and displaying interface documents
- Inability to re-use common parts between specification files
- Trouble with referencing outside documents

![Image](https://user-images.githubusercontent.com/60163079/178050189-c3afe457-3ccf-49df-8a6d-6c9d84c9a756.png)


## What's next?
With this information, we can target one of these problem spaces and work to come up with solutions to these problems within tooling.

**Comment by derberg** [comment]
oh jizz, what a mix of docs tools 👀 

so much effort and only 24 responses 🤔

**Comment by mcturco** [comment]
@derberg I know :( I think in the future we could get more responses if all or most of the questions were multiple choice. People don't like to type words! Haha

**Comment by derberg** [comment]
yeah, we definitely need to research @mcturco 
I received this comment https://www.linkedin.com/feed/update/urn:li:activity:6939499012697817088?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6939499012697817088%2C6940791565145538560%29 on LinkedIn. Not much helpful if it comes to ideas, but pretty clear with the message - forms take time and people do not like them

**Comment by mcturco** [comment]
It seems like that person is saying that there could be a better way to collect data for user experience than Google Forms. There are other paid tools we could use, but yeah I think at this stage in the project we don't have an overwhelming user base just yet where a tool like that would be worth the cost IMO

**Comment by derberg** [comment]
sure, but we can always experiment. Do you remember the form for AsyncAPI Conference we had on the conference website? Technically it was just a custom form and from client-side we sent data to Google Form and then through some no-code integration (@AceTheCreator correct me if I'm wrong) we had the data listed in Google Spreadsheet, so I could later easily summarize the results.

**Comment by AceTheCreator** [comment]
@derberg You're absolutely right! @mcturco i think you should look into what Lukasz is suggesting :)

**Comment by mcturco** [comment]
@derberg @AceTheCreator Yeah I think that is a great idea! I saw that you guys got a ton of responses too (it was multiple choice). Is this fairly easy to add, just for future reference?

**Comment by AceTheCreator** [comment]
@mcturco yes it's easy to add. @derberg @mcturco what if we make a customizable component that can be easily reusable anywhere at any time?

**Comment by mcturco** [comment]
@AceTheCreator Sure thing!
