### ISSUE TITLE
Fonts broken in 1.0.0-next.25

### ISSUE THREAD

**Issue by acelaya** [asyncapi/asyncapi-react#602]
**Description**

The CSS fonts seem to have been broken in v1.0.0-next.25. I beleive it is related with the scoped CSS from here https://github.com/asyncapi/asyncapi-react/pull/493

**Expected result**

Using v1.0.0-next.25 or higer, the fonts should look like this:

![Captura desde 2022-05-27 10-05-51](https://user-images.githubusercontent.com/2719332/170658356-a57d8d8c-9934-4989-81ce-fa0fc0b87784.png)

**Actual result**

The fonts are now using default one:

![Captura desde 2022-05-27 10-07-12](https://user-images.githubusercontent.com/2719332/170658507-5321ad99-cc15-47d0-8d03-c920ec90a103.png)

**Steps to reproduce**

Install v1.0.0-next.25 or higher, and see how it looks.

**Comment by magicmatatjahu** [comment]
@acelaya Hello! Yes, we removed global styling due to fact that some people had problem with it - they use their company fonts and want to override default one. Here is a doc https://github.com/asyncapi/asyncapi-react/tree/next#custom-styles how to apply fonts :)

**Comment by acelaya** [comment]
Thanks!

**Comment by acelaya** [comment]
This worked perfectly. Thanks!
