### ISSUE TITLE
How to use pretty template from playground app? 

### ISSUE THREAD

**Issue by vanyakosmos** [asyncapi/asyncapi-react#610]
**Description**

For the playground app you have pretty and functional template, with tags aggregation, collapsed examples and literally everything that I need.

But with web-components I can use only template with fiory.css:

```
<script src="https://unpkg.com/@asyncapi/web-component@0.24.22/lib/asyncapi-web-component.js" defer=""></script>
<asyncapi-component schemaurl="/asyncapi.json" cssimportpath="https://unpkg.com/@asyncapi/react-component@0.24.22/lib/styles/fiori.css">
</asyncapi-component>
```

And it doesn't look as pretty as the one in the playground. 

So, how can I use styles/components from the playground app instead of default ones?

(preferably by simply changing `src` in web-component config)

**Reasons**

I need more functionality and less eyes pain.

**Attachments**

Sweet sweet playground template:

<img width="1792" alt="Screenshot 2022-06-14 at 19 32 36" src="https://user-images.githubusercontent.com/16745500/173629562-8ec4630d-30a6-4c58-b5b3-88c0c88b92e1.png">

**Comment by vanyakosmos** [comment]
how can I find stable (or at least semi-stable) version of the **next** version of the component?

because right now: 

- component doesn't hide schemas and servers, but config seems find: `config='{"show": {"sidebar": true, "schemas": false, "messages": false}, "sidebar": {"showOperations": "byOperationsTags"}}'`
- scrolling to the anchor doesn't work

![d1](https://user-images.githubusercontent.com/16745500/173667441-55845bfa-ca6a-4521-90af-e4a540f4ec30.gif)

**Comment by magicmatatjahu** [comment]
Thanks for info! I know where the bug is. When I get back from vacation I will fix it.

> how can I find stable (or at least semi-stable) version of the next version of the component?

Stable is the latest.
