### ISSUE TITLE
DocsUI: UX/UI updates

### ISSUE THREAD

**Issue by mcturco** [asyncapi/asyncapi-react#617]
**Description**
Just wanted to open this issue as I have been working on some UX/UI updates to the documentation components and wanted to create a "home" to post some iterations and get some feedback from the community.

I have an idea to rename this repo: **DocsUI** `asyncapi/docs-ui` for when the first iteration of these component updates are complete. That way we can package these components and allow for others to use each one in their own projects where they are outputting documentation with their asyncapi files. Would like to know everyone's thoughts on that!

There are a quite a few different improvements we need to make, so wanted to break them down into separate tasks to make it easier to keep track of. I could also break these out into separate issues for each one if that is easier?

### Scope

- [ ] Sidebar Navigation
- [ ] Info Object output
- [ ] Servers Object output
- [ ] Operations Object output
- [ ] #618 
- [ ] Examples output
- [ ] Schema output

> Schema output: added this for now, but I think we should discuss if this is needed for docs output.

We can definitely add more to this list if needed, but I think these components are the foundation of the DocsUI so we can make a lot of great updates just by re-designing these.

**Comment by magicmatatjahu** [comment]
I love it ❤️ 

> I have an idea to rename this repo: DocsUI asyncapi/docs-ui for when the first iteration of these component updates are complete. That way we can package these components and allow for others to use each one in their own projects where they are outputting documentation with their asyncapi files. Would like to know everyone's thoughts on that!

We have similar issue for that I added suggestion to have only `@asyncapi/ui` like here https://github.com/asyncapi/asyncapi-react/issues/263#issuecomment-822742355 By this we can have several kits in single project :) About packaging: if we will write everything by ESM (EcmaScript Modules) users will have option to use only needed components and rest will be shaking from final app. In our cases with kits I'm not a fan of multiple repositories and packages, one should be enough :)

> Schema output (added this for now, but I think we should discuss if this is needed for docs output)

It's probably one of most important and probably hardest to implement component because we render `channel parameters`, `server variables`, `message payload/headers` by this component, so in the `Messages Object output` we should use that Schema component.

**Comment by mcturco** [comment]
> We have similar issue for that I added suggestion to have only @asyncapi/ui like here https://github.com/asyncapi/asyncapi-react/issues/263#issuecomment-822742355 By this we can have several kits in single project :)

This sounds great to me! Whatever you think makes sense from a technical standpoint 😄 

> It's probably one of most important and probably hardest to implement component because we render channel parameters, server variables, message payload/headers by this component, so in the Messages Object output we should use that Schema component.

I guess my question relates more to the idea to only remove the Schemas section in the documentation output because it is redundant. If we just show the schema at each message level, it might be a better experience rather than telling the user to go somewhere else to view the message schema. Not sure if that makes sense, but I know @fmvilas mentioned this to me once before as well so maybe he can shed more light on the topic 😄

**Comment by magicmatatjahu** [comment]
But schemas section can always be removed from the generated UI via config.  

> If we just show the schema at each message level, it might be a better experience rather than telling the user to go somewhere else to view the message schema.

I see your point of view, but we render schema for payload etc in place where we should, we don't make a link to the schema section. As Fran said, it's only for developers.

I hope it's clear now :)

**Comment by fmvilas** [comment]
Still way relevant 😄

**Comment by asmitbm** [comment]
Hey @mcturco,

I'm interested to work on this issue!

**Comment by AceTheCreator** [comment]
Hey Folks, 

To clarify how to submit a proposal, you should contact the project Mentor/s on Slack and send them your submission in the form of a document or ask them how best they'd prefer you submit your proposals.

**Comment by asmitbm** [comment]
Keep it open github-actions :)
