### ISSUE TITLE
Support missing fields/objects from spec 2.0.0

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/asyncapi-react#63]
**Description**

At the moment we support a main part of spec in rendering, but there are also parts that we don't, like `bindings`, `properties` from `schema` (min, max, type etc) - https://github.com/asyncapi/asyncapi/blob/master/versions/next/asyncapi.md#properties, externalDocs, tags, correlationID etc.

AC:
- support all missing fields/objects in rendering. With any question about design/styling, please contact with @fmvilas or our designers.

List:
- [X] `properties` from `schema` (min, max, type etc), - https://github.com/asyncapi/asyncapi-react/commit/6e2eeeea3b4431b7e6bec9abd7425d0c6c26a5eb,
- [X] bindings - https://github.com/asyncapi/asyncapi-react/pull/259
- [X] externalDocs - https://github.com/asyncapi/asyncapi-react/pull/327
- [X] tags - https://github.com/asyncapi/asyncapi-react/pull/327
- [X] correlationID - https://github.com/asyncapi/asyncapi-react/pull/327

Updated list (4 May 2021):
- [x] dependencies in JSON Schema visualiser - https://github.com/asyncapi/asyncapi-react/pull/334
- [x] true/false JSON Schemas - https://github.com/asyncapi/asyncapi-react/pull/367
- [x] id https://github.com/asyncapi/asyncapi-react/pull/345
- [x] operationId https://github.com/asyncapi/asyncapi-react/pull/345
- [x] externalDocs in operation https://github.com/asyncapi/asyncapi-react/pull/345
- [ ] discriminator in AsyncAPI JSON Schema - it will be handled in https://github.com/asyncapi/html-template/issues/68

**Comment by fmvilas** [comment]
FYI, protocolInfo = bindings. Bindings is the new name.

**Comment by hesyar** [comment]
We need this feature too.

**Comment by GreenRover** [comment]
+1

**Comment by derberg** [comment]
@hesyar this component was donated by the team behind this project https://kyma-project.io/ and they are main maintainers atm. Afaik, they are super busy atm at least until May. Would it be something you could contribute? AsyncAPI core team is more focused on generator and parser to have 1.0 release for both

**Comment by hesyar** [comment]
Hi @derberg thanks for your reply. For what I can do now is to update the parser version. Furthermore I'll try to contribute more if I find any time. Thanks, I'll let you know as soon as I've the new version.

**Comment by derberg** [comment]
@magicmatatjahu I thought `properties from schema (min, max, type etc) - https://github.com/asyncapi/asyncapi/blob/master/versions/next/asyncapi.md#properties` is already supported?

**Comment by magicmatatjahu** [comment]
@derberg Yes, I updated the issue description with list

**Comment by derberg** [comment]
awesome, we need to add correlationID and also update the readme then

**Comment by magicmatatjahu** [comment]
In [`1.0.0-next.1`](https://github.com/asyncapi/asyncapi-react/pull/327):

- supporting almost everything from JSON Schema draft-07 except `dependencies` and `true/false` schemas (due to bug in parser https://github.com/asyncapi/parser-js/issues/232)
- supporting from AsyncAPI 2.0.0 everything except:
  - `id`
  - `operationId`
  - `externalDocs` in operation
  - `discriminator` in AsyncAPI JSON Schema

**Comment by magicmatatjahu** [comment]
In `1.0.0-next.9`:

- support Boolean (true/false) JSON Schemas - https://github.com/asyncapi/asyncapi-react/pull/367

Discriminator will be handled under https://github.com/asyncapi/html-template/issues/68 issue.
