### ISSUE TITLE
Slotting mechanism for extra HTML content

### ISSUE THREAD

**Issue by W0nderMuffin** [asyncapi/asyncapi-react#645]
**Description**

Add possibility to inject custom HTML into "slots".

**Reasons**

E.g. we want to enrich the rendered output with additional information from external sources which are not included in the origin async api spec file.

Currently we have to override a existing description property of a spec file with inline html to get the desired result.

It would be nice to have something like a slotting mechanism for extra html.

**Attachments**

Example from OAS viewer [RapiDoc](https://github.com/rapi-doc/RapiDoc):
![grafik](https://user-images.githubusercontent.com/9134093/191687547-f4e3ef69-c14e-444f-90bb-be980849feba.png)

**Comment by pboth1304** [comment]
I would appreciate such feature 👍🏼
