### ISSUE TITLE
Double negated validation rules not being displayed

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/asyncapi-react#662]
**Description**

With JSON Schema if you do double negation such as:
```yaml
asyncapi: '2.5.0'
info:
  title: 'Account Service'
  version: '1.0.0'
  description: 'This service is in charge of processing user signups'
channels:
  user/signedup:
    publish:
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        $ref: '#/components/schemas/UserSignedUpPayload'
  schemas:
    UserSignedUpPayload:
      not: 
        not: 
          type: 'object'
          allOf: 
            - $ref: '#/components/schemas/EmailProperty'
            - $ref: '#/components/schemas/DisplayNameProperty'
    EmailProperty:
      properties:
        email: 
          type: 'string'
          format: 'email'
          description: 'Email of the user'
    DisplayNameProperty:
      properties:
        displayName:
          type: 'string'
          descripion: 'Name of the user'
```

It is displayed as:
![image](https://user-images.githubusercontent.com/13396189/199486647-bcd9f075-20c8-456d-b0fa-01be1661e4f9.png)

This is incorrect, as we double negate it meaning it's allowed.

**Comment by magicmatatjahu** [comment]
`Cannot adhere to` -> `Cannot adhere to` is a true, double negation is true, so it shows correctly 😄 Take into account that next to the `not` and `allOf` you can add other things like `type`, `anyOf` etc so not always double negation will give you true - then we would somehow filter all the fields, and this is difficult and in the component itself we should not do it (in a separate library ok).

**Comment by jonaslagoni** [comment]
Wait, I fucked up yea 😆 I don't know why but just read the `Never` part to the right side and that just didn't click that it also said `Cannot adhere to`.

My bad!
