### ISSUE TITLE
Build fails on Node 18 LTS

### ISSUE THREAD

**Issue by shishkin** [asyncapi/asyncapi-react#691]
**Description**

When installing dependencies and bootstrapping (`npm i`) the `webpack` bundle step fails with `ERR_OSSL_EVP_UNSUPPORTED` OpenSSL error. This is due to an issue in [webpack 4](https://github.com/webpack/webpack/issues/14532#issuecomment-947513562).

Suggest to update webpack to the latest version that uses supported crypto algorithms.

**Expected result**

Build succeeds.

**Actual result**

Build fails.

**Steps to reproduce**

Run `npm i` on latest `next` branch under Node 18.

**Troubleshooting**

Workaround is to run `npm` with legacy node option: `NODE_OPTIONS=--openssl-legacy-provider npm i`

**Comment by magicmatatjahu** [comment]
I would not like to move to webpack v5 for now (we can but not need to) - there is a workaround for this as in this file:

https://github.com/asyncapi/studio/blob/master/craco.config.js#L66

**Comment by aeworxet** [comment]
Current workarounds for Node.js 18+, in order for the whole project not to fail on `npm install` / `npm start`, would be
```diff
diff --git a/package.json b/package.json
index 942b3ae..2558899 100644
--- a/package.json
+++ b/package.json
@@ -14,7 +14,7 @@
   "scripts": {
     "bootstrap": "lerna bootstrap",
     "clean": "lerna clean",
-    "start": "lerna exec --parallel -- npm run start",
+    "start": "lerna exec NODE_OPTIONS=--openssl-legacy-provider --parallel -- npm run start",
     "test": "cd library && npm test",
     "build": "npm run build:library && npm run build:webcomponent && npm run build:playground",
     "build:library": "cd library && npm run prepare",
diff --git a/web-component/package.json b/web-component/package.json
index ede6610..7b073c7 100644
--- a/web-component/package.json
+++ b/web-component/package.json
@@ -38,7 +38,7 @@
   ],
   "scripts": {
     "start": "tsc --watch",
-    "bundle": "webpack",
+    "bundle": "export NODE_OPTIONS=--openssl-legacy-provider && webpack",
     "prepare": "npm run bundle",
     "prepack": "cp ../README.md ./README.md && cp ../LICENSE ./LICENSE",
     "postpack": "rm -rf ./README.md && rm -rf ./LICENSE",
```
until the issue is fixed permanently.
