### ISSUE TITLE
Async API Editor with Web Component ?

### ISSUE THREAD

**Issue by doki97** [asyncapi/asyncapi-react#698]
We are using the @asyncapi/web-component v0.24.23 inside a Svelte application to preview different Async API specifications. However it is also planned to extend this view with an edit functionality (as used in the "old" Playground or Studio now).

![grafik](https://user-images.githubusercontent.com/103121536/216063109-99f5e9b6-dd02-40a3-90f4-2e86d8ab5388.png)

Is there some way to include this Editor to the Web Component ? I have seen that there is some source code inside the [playground ](https://github.com/asyncapi/asyncapi-react/tree/master/playground) folder, however this does not seem to be available in the Web Component.

I have also seen that there has been similar requests in the past for something like this, so are there any news regarding this or am i missing something ?

Thanks in advance

**Comment by magicmatatjahu** [comment]
@doki97 Hi! Do you wanna use Editor like in Studio in your app (together with web-component) or you wanna test web-component with editor (you edit something and you see changes, only in "playground"). If this first, we have issues for that https://github.com/asyncapi/asyncapi-react/issues/146. If this second, you should try to integrate the `monaco-editor` as we did in studio https://github.com/asyncapi/studio/blob/master/src/index.tsx#L15 

Also, you probably know, bu you're using the old `web-component` version, you should try to migrate to the `@asyncapi/react-component@next` to have view like in Studio.

I will look in upcoming days how to publish Studio as separate, standalone React component.

**Comment by doki97** [comment]
@magicmatatjahu Yes, the first one would be my use case. Thanks for your reply and looking forward to it

**Comment by magicmatatjahu** [comment]
@doki97 Did you use proper css file? We have new path of styles in `@next` version:

https://github.com/asyncapi/asyncapi-react/tree/next#default-styles

```js
import "@asyncapi/react-component/styles/default.css";
// or minified version
import "@asyncapi/react-component/styles/default.min.css";
```

**Comment by doki97** [comment]
@magicmatatjahu  Thank you, i still used the old style path...  That fixed it now 👍

**Comment by doki97** [comment]
@magicmatatjahu Hi, any updates on the standalone Studio/Editor Component ?
