### ISSUE TITLE
Not able to use this with Vite. How?

### ISSUE THREAD

**Issue by fhareide** [asyncapi/asyncapi-react#703]
I'm trying to use this package in a Vite project but get "Uncaught ReferenceError: process is not defined". 

I have not found out how to use a version that work with Vite. Any help is much appreciated. And maybe it should be added to documentation?

**Comment by magicmatatjahu** [comment]
@fhareide Hi! Thanks for the issue! Are you using Vite + React or Vite + another render lib/framework? Maybe there's a problem. How exactly are you using component - normal React component, component without parser or standalone component?

**Comment by fhareide** [comment]
Vite + react. I have tried all combinations I could think of. It's not totally clear to me how to set it up with the different methods.

**Comment by fhareide** [comment]
@magicmatatjahu Any news on this one?

**Comment by Ferror** [comment]
Hey! Wanted to let you know that I also struggle with the same problem. First thought it is the framework problem, but then I can't even make it work with webpack etc.

**Comment by Ferror** [comment]
@magicmatatjahu I used the `next` branch and created very simple usage for the Async API component and published it here. https://github.com/Ferror/asyncapi-component-vite The only thing that can be seen is an error below

```txt
Uncaught ReferenceError: process is not defined
    at node_modules/@apidevtools/json-schema-ref-parser/lib/util/url.js (url.js:3:29)
    at __require2 (chunk-6FBSFQRG.js?v=f184a0b1:18:50)
    at node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js (pointer.js:6:13)
    at __require2 (chunk-6FBSFQRG.js?v=f184a0b1:18:50)
    at node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js (ref.js:5:17)
    at __require2 (chunk-6FBSFQRG.js?v=f184a0b1:18:50)
    at node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js (refs.js:4:14)
    at __require2 (chunk-6FBSFQRG.js?v=f184a0b1:18:50)
    at node_modules/@apidevtools/json-schema-ref-parser/lib/index.js (index.js:4:15)
    at __require2 (chunk-6FBSFQRG.js?v=f184a0b1:18:50)
```

**Comment by meiyananthamp** [comment]
I am also facing the same issue.

**Comment by mr-nuno** [comment]
Any progress on this? Really want to migrate away from CRA.

**Comment by dansiemens1** [comment]
Also having this issue. CRA is no longer recommended by React so I imagine this will get more attention as time goes on. 

> Vite project but get "Uncaught ReferenceError: process is not defined".

To work around this part, I added to my `vite.config.ts`: 
```
define: {
    'process.env': {},
},
```

However now I'm getting the error:
> [constate] Component not wrapped within a Provider. constate.es.js:12:14

Any further investigation done into this problem? @magicmatatjahu

**Comment by edwmurph** [comment]
<details>
<summary>i'm hitting this same issue and was able to workaround it with the following diff:</summary>

```
diff --git a/client/components/asyncapi.jsx b/client/components/asyncapi.jsx
index 7ffefd5..5a69107 100644
--- a/client/components/asyncapi.jsx
+++ b/client/components/asyncapi.jsx
@@ -1,5 +1,18 @@
+import { useEffect } from 'react';
+import AsyncApiStandalone from '@asyncapi/react-component/browser/standalone';
+
+// eslint-disable-next-line max-len
+const schema = '{"asyncapi":"2.4.0","info":{"title":"Account Service","version":"1.0.0","description":"This service is in charge of processing user signups"},"channels":{"user/signedup":{"subscribe":{"message":{"$ref":"#/components/messages/UserSignedUp"}}}},"components":{"messages":{"UserSignedUp":{"payload":{"type":"object","properties":{"displayName":{"type":"string","description":"Name of the user"},"email":{"type":"string","format":"email","description":"Email of the user"}}}}}}}';
+
 export default function AsyncAPI() {
+  useEffect( () => {
+    AsyncApiStandalone.render(
+      { schema, config: {} },
+      document.getElementById('asyncapi-component')
+    );
+  }, [] );
+
   return (
-    <div>asyncapi</div>
+    <div id='asyncapi-component'/>
   );
 }
diff --git a/client/index.jsx b/client/index.jsx
index cb26f0d..7fdba90 100644
--- a/client/index.jsx
+++ b/client/index.jsx
@@ -3,6 +3,7 @@ import 'primereact/resources/primereact.min.css';
 import 'primeicons/primeicons.css';
 import 'primeflex/primeflex.css';
 import 'swagger-ui-react/swagger-ui.css';
+import '@asyncapi/react-component/styles/default.css';
 import './global.css';
 import React from 'react';
 import ReactDOM from 'react-dom/client';
diff --git a/package.json b/package.json
index 7fcb900..12abc35 100644
--- a/package.json
+++ b/package.json
@@ -13,6 +13,7 @@
     "lint:fix": "eslint . --ext .mjs,.jsx --fix"
   },
   "dependencies": {
+    "@asyncapi/react-component": "1.0.0-next.48",
     "@aws-sdk/client-s3": "3.363.0",
     "@koa/router": "12.0.0",
     "dotenv": "16.3.1",
```
</details>

<details>
<summary>but i don't think the styling of the render looks good so i probably won't move forward with asyncapi documentation at this time</summary>
<img width="1437" alt="image" src="https://github.com/asyncapi/asyncapi-react/assets/20996513/06f04077-e1f3-412b-ae28-590b364bbc38">
</details>

**Comment by stewartmoreland** [comment]
Encountering the same error. Any updates?

Vite v4.3.9
React v18.2.0
Node v18.16.1

**Comment by mr-nuno** [comment]
Maybe all of you already has figured this out but you can use the standalone version of the component with vite.
`"@asyncapi/react-component": "^1.0.0-next.44",`

```
./src/global.d.ts
declare module '@asyncapi/react-component/browser/standalone';

./src/components/AsyncApiSpecification.tsx
export const AsyncApiSpecification: React.FC = () => { 
    useEffect(() => {
                    AsyncApiStandalone.render({
                        schema: '<specification-data>',
                        config: {
                          schemaID: 'custom-spec',
                          show: {
                            operations: true,
                            errors: true,
                          },
                        },
                      }, document.getElementById('asyncapi'));
    }, []);

    return (
        <div id="asyncapi"></div>    
    );
}

**Comment by dansiemens1** [comment]
@mr-nuno's answer is almost complete. This will display the asyncapi doc, but without any formatting. You need to go one step further to inject the JS and the CSS.

> ./src/global.d.ts
```
declare module '@asyncapi/react-component/browser/standalone';
declare module '@asyncapi/react-component/browser/standalone/index';
```

> ./src/components/AsyncApiSpecification.tsx
```
import asyncApiJs from '@asyncapi/react-component/browser/standalone/index.js'
import asyncApiCss from '@asyncapi/react-component/styles.default.min.css'

...

return (
  <link rel='stylesheet' type='text/css' href={asyncApiCss} />
  <script src={asyncApiJs}></script>
  <div id="asyncapi"></div>
);
```

**Comment by mr-nuno** [comment]
correct @dansiemens1, sorry about that :-)
