### ISSUE TITLE
[next] Group channels by name?

### ISSUE THREAD

**Issue by Tinche** [asyncapi/asyncapi-react#705]
Howdy folks,

I'm attempting to document a websocket API using asyncapi and asyncapi-react.

Websockets are bidirectional, so they often have both PUB and SUB parts. Since upgrading to `next` I've noticed the PUB and SUB parts of a channel are rendered separately (or, more separately than in the old version). The description of the channel is also rendered twice. Is there any way to unify them visually? I feel like my users (who aren't expected to be too tech savvy) might be less confused with an approach like this.

In any case, thanks for the library!

**Comment by derberg** [comment]
Have a look at https://github.com/asyncapi/asyncapi-react/blob/next/docs/configuration/config-modification.md

```
  sidebar?: {
    showServers?: 'byDefault' | 'bySpecTags' | 'byServersTags';
    showOperations?: 'byDefault' | 'bySpecTags' | 'byOperationsTags';
  },
```

but this is all about sidebar navigation.

I'm not 100% sure but I guess you are referring not to navigation but the main content? If yes then I would need to see some mockup to fully understand
