### ISSUE TITLE
CSP violation 'script-src' 'unsafe-eval' in web-component and standalone package in angular

### ISSUE THREAD

**Issue by mbmwlr** [asyncapi/asyncapi-react#725]
**Description**
We are trying to implement the asyncapi renderer within an Angular application.
When adding a Content Security Policy limiting the 'script-src' to 'self', the package is blocked, as some the package tries to execute code via 'unsafe-eval'.

We tried both the web-component as well as the standalone version available in the 'next' branch.
Both yield the same result.

**Expected result**
Restrictive CSP is possible to enforce while using the package.

**Actual result**
CSP blocks the package.

**Steps to reproduce**
I compiled a small sample project demonstrating the error:
https://github.com/mbmwlr/angularAsyncApiTest

**Troubleshooting**
We are actively investigating the problem. If I have further information to narrow it down which package or line of code causes it, I will update.

Edit: This could be related, but not sure yet if and how it applies here:
https://github.com/okta/okta-auth-js/issues/1128

**Comment by derberg** [comment]
@mbmwlr do you have ideas how to solve it?

**Comment by mbmwlr** [comment]
No, unfortunately not. I think maybe a package update is a viable option to explore, as it seems to be caused by an outdated dependency. But did not have the time to try it in depth. Initial try broke the whole package for me.

**Comment by theycallmewolf** [comment]
Hey @mbmwlr and @derberg. By any chance you manage to fix this or did you find any alternative?
Thanks in advance

**Comment by MelleD** [comment]
@mbmwlr Were you able to solve the problem?
