### ISSUE TITLE
Mark channels as deprecated as pr the spec

### ISSUE THREAD

**Issue by mifriis** [asyncapi/asyncapi-react#726]
**Description**

Hi folks, 

The AsyncAPI specification seems to support deprecation of channels (mentioned in Fixed Fields on https://www.asyncapi.com/docs/reference/specification/v2.3.0) but doesn't seem to have any effect on how a channel is displayed in the UI component.

It would be cool if it followed the same approach as OpenAPI by greying it out or similar.

**Reasons**

As new event formats, guidelines and similiar start to emerge in our organization, the need to move ahead to different ways to expose messages and chanels without breaking consumers/producers integration becomes increasingly important.

This react component is our primary way of viewing the spec.

As a consumer of an AsyncAPI I would like to know which channels are deprecated so i may choose the most relevant in case there is an overlap.

As a producer of events I would like to have the ability to provide an upgrade path to my consumers in case a channel is deprecated.

**Attachments**

Example from OpenAPI & Swagger
<img width="715" alt="image" src="https://github.com/asyncapi/asyncapi-react/assets/1443594/1788676f-51c4-4091-939f-7a4a6488e95b">

**Comment by derberg** [comment]
@mifriis `deprecated` is mentioned in a spec as additional field you can use in the AsyncAPI Schema, when describing message `payload`. It is not channel related. 

what you need is not in place yet, as there was no interest in the community. I recommend you join https://github.com/asyncapi/spec/issues/305 and for now I would close this issue. Are you ok with that?
