### ISSUE TITLE
Hidden (via config) "messages" and "schemas" show up in sidebar

### ISSUE THREAD

**Issue by rajashekars** [asyncapi/asyncapi-react#727]
#### Describe the bug
The below config was used to generate the html template. `messages` and `schemas` are configured to be hidden in the main panel and this works as expected. Though the side bar shows these features. Since they are hidden in the main panel, they should ideally be hidden in the side bar.

```
{
  "show": {
    "sidebar": true,
    "info": true,
    "servers": true,
    "operations": true,
    "messages": false,
    "schemas": false,
    "errors": true
  },
  "expand": {
    "messageExamples": false
  }
}
```

#### How to Reproduce
Create config file
```
{
  "show": {
    "sidebar": true,
    "info": true,
    "servers": true,
    "operations": true,
    "messages": false,
    "schemas": false,
    "errors": true
  },
  "expand": {
    "messageExamples": false
  }
}
```

Run command
`ag asyncapi-spec.yml @asyncapi/html-template -o output -p config=config.json`

#### Expected behavior
`messages` and `schemas`  should be hidden in the side bar.

**Comment by derberg** [comment]
moved to react component repo as in html template we just pass config to component without any modifications
