### ISSUE TITLE
Types not available for angular

### ISSUE THREAD

**Issue by ImPacific** [asyncapi/asyncapi-react#728]
**Description**
While trying to use the React AsyncAPI component as suggested in [wiki](https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/angular.md) as a `AsyncApiStandalone` bundle the types should be provided. 

**Reasons**
The component should work with frameworks other than React as well

**Attachments**

![image](https://github.com/asyncapi/asyncapi-react/assets/6881755/ecd0c424-866a-4931-96fe-6bdd08165290)

**Comment by anj20** [comment]
Ig we jst need to define a AsyncApi document data and  pass it to the component. Then we re good to go!

**Comment by derberg** [comment]
If you folks know the best way to solve it, we are happy to accept PRs
