### ISSUE TITLE
Error: Version 2.6.0 is not supported

### ISSUE THREAD

**Issue by Spooky063** [asyncapi/asyncapi-react#729]
When I try to implement the web component with an asyncapi file, I have an error message related to the version of the specification.
I try with differents versions to implement it (master and next) and no one works.

I create a sandbox to reproduce my issue: https://codesandbox.io/s/asyncapi-async-ngd0v

Maybe I forgot something but I follow the documentation and there is no mention of version restriction.

**Comment by derberg** [comment]
Hey, thanks for the report

Always use `next` but latest, latest is 47 and this is when 2.6 was enabled =>  https://github.com/asyncapi/asyncapi-react/releases/tag/v1.0.0-next.47

**Comment by Spooky063** [comment]
Thank you, it's works perfectly.

You can close the issue.
