### ISSUE TITLE
AsyncAPI spec v3 support in React components

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/asyncapi-react#733]
### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

### Scope
- [x] Migrate to new JS parser API
- [x] https://github.com/asyncapi/parser-js/issues/780
- [x] Add support for request/reply
- [x] https://github.com/asyncapi/asyncapi-react/issues/815
- [x] Make sure navigation adapts to multiple operations

**Comment by fmvilas** [comment]
Added "Add support for every new v3 feature" to the list of remaining tasks.

**Comment by fmvilas** [comment]
/progress 30 First PR in place: https://github.com/asyncapi/asyncapi-react/pull/746.

**Comment by fmvilas** [comment]
/progress 60 React component now supports the new Parser API 🎉 Kudos to @jonaslagoni for pushing it 🙌

**Comment by fmvilas** [comment]
/progress 75 @jonaslagoni is working on adding request/reply support in this PR: https://github.com/asyncapi/asyncapi-react/pull/749.

**Comment by jonaslagoni** [comment]
/progress 75 @AceTheCreator working on the request/reply stuff here: https://github.com/asyncapi/asyncapi-react/pull/795

**Comment by jonaslagoni** [comment]
/progress 90 @AceTheCreator almost done 💪 Just need final review from @derberg

**Comment by derberg** [comment]
request reply done https://github.com/asyncapi/asyncapi-react/releases/tag/v1.2.0 but it also showed how buggy parser is
