### ISSUE TITLE
AsyncAPI renderer crashing

### ISSUE THREAD

**Issue by char0n** [asyncapi/asyncapi-react#745]
Hi everybody,

I've noticed that on following AsyncAPI 2.6.0 document, the renderer catastrophically crashes. There is no way of recovery. This also manifest in https://studio.asyncapi.com/ where the document is stored in local storage under `document` key and subsequent refreshes results in never ending splash screen.

Affected version: `@asyncapi/react-component =1.0.0-next.48`

**Document**:
```yaml
asyncapi: '2.6.0'
info:
  title: AsyncAPI
  version: '1.0.0'
channels:
  'foo':
    description: Bar.
    publish:
      message:
        oneOf:
          - $ref: '#/components/messages/Foo'
       
          
components:
  messages:
    Foo:
      name: Foo
      payload:
        $ref: "#/components/schemas/Bar"
      examples:
        - name: standard
          payload:
            after: 
              oneOf:
              - $ref: '#/components/messages/Foo'
              
  schemas:
    Bar:
      type: object
      properties:
        eventType:
          type: string
          desciption: Foo
```

**Never ending splash screen:**

![image](https://github.com/asyncapi/asyncapi-react/assets/193286/10cfebb5-0285-4001-a13b-388ffa9d82fe)

**Comment by magicmatatjahu** [comment]
@char0n Circular references in message examples aren't supported, only in schemas.

**Comment by char0n** [comment]
@magicmatatjahu yep I do understand that, thus I would expect the renderer to treat the `$ref` field as normal field name without any significance. Even if it would be supported still I wouldn't expect the render to crash and properly recover.

**Comment by magicmatatjahu** [comment]
The parser tries to resolve the references and we do not exclude the refs in the payload's examples, they are still resolved. In addition, the validator checks whether the example from payload agrees with the schema defined in payload. In your case, your schema would not pass anyway.

**Comment by magicmatatjahu** [comment]
So `Message Example Object`.payload is not "any" in the sense of parser/validator.

**Comment by char0n** [comment]
Right, so it's basically an arbitrary `data` (that's what `any` means for me) that needs to be validated later against `Message.payload`, but it's still just `data`. If the `Message.payload` is defined as empty schema `{}` then the validation would always pass. But that's not the issue here.

```yaml
asyncapi: '2.6.0'
info:
  title: AsyncAPI
  version: '1.0.0'
channels:
  'foo':
    description: Bar.
    publish:
      message:
        oneOf:
          - $ref: '#/components/messages/Foo'
       
          
components:
  messages:
    Foo:
      name: Foo
      payload:
        $ref: "#/components/schemas/Bar"
      examples:
        - name: standard
          payload:
            after: 
              oneOf:
              - $ref: '#/components/messages/Foo'
              
  schemas:
    Bar: {}
```

The issue seem to be in following:

> The parser tries to resolve the references and we do not exclude the refs in the payload's examples

This shouldn't happen, it seems that the tooling goes outside the spec here. But that's not what concerns me as well. 

What concerns me is that the actual crash happens. In AsyncAPI studio you see the white screen, and after the reload you'll just see the splash screen indefinitely.  You need to know how to delete `localStorage` to be able to work with https://studio.asyncapi.com/ again.

**Comment by char0n** [comment]
Still reproducible in latest studio version.
