### ISSUE TITLE
Provide an Angular-Component

### ISSUE THREAD

**Issue by mischahaenen** [asyncapi/asyncapi-react#75]
**Description**
For my company I integrate the Kafka API's into the Angular website. The goal is to be able to display and manage the APIs. I am currently integrating the React component into the existing Angular application.
I realized this with the contribution of Stackoverflow: https://stackoverflow.com/questions/47714221/using-react-component-library-in-an-angular-4-application. So the compatibility with Angular applications would be given.

**Reason**
Currently it is difficult to test or debug the React component. I can't derive errors well either. I think these bugs could be fixed if you offered an Angular component. Alternatively, web components are certainly possible. API management is not well known at the moment but I think that many developers will be happy if a component would be available.

**Comment by derberg** [comment]
Hey, you can close but only if you are not interested in contributing Angular component together :) so the thing is, keeping 3 components up to date is hard, but we could together maybe come up with a good idea how to do it efficiently. Maybe some code can be abstracted to separate npm modules and reused in those different components. Maybe we could do something to make working on components for different frameworks much more pleasure and not a nightmare :D

Of course at the end it all depends, how hard it really is to maintain react component in angular app, is it so hard that it is better to work on separate Angular component.

**Comment by mischahaenen** [comment]
Good idea :) my idea would be that you make a bundle out of the react component. the practical thing would be that you don't have to compile the component anymore and could integrate it into all frameworks as well as angular. Plus you only have to update one component. I have already integrated the SwaggerUIBundle (https://github.com/activelamp/swagger-ui-bundle) and it works fine in my application. It would be cool if you could publish it, so the bundle is always up to date. Embedding a React component is actually not a problem, but when compiling it comes to errors so I came up with the idea of creating a bundle. What do you think about it?

**Comment by derberg** [comment]
tbh I've never met before with the solution you proposed, and the fact that the repo you linked is not actively maintained for years do not make me an optimist here :)

I checked with @aerfio and @magicmatatjahu and we have a `?` mark here. Is this known pattern, do you know some articles or other examples that follow the same approach?

**Comment by derberg** [comment]
What about some recent patterns, like wrapping react in web component, or maybe this approach backed by Microsoft https://github.com/microsoft/angular-react ?

**Comment by aerfio** [comment]
Some comments here from my side: same thing as @derberg said about that one repo, without much investigation I'd gravitate towards something like swagger-ui-**_dist_**, or maybe web components

Another thing is that debugging react apps should be easier than some kind of wierd wrapper, so maybe instead we should provide stricter checking of component props? Or somehow increase this components usability in non-react apps, if such need arise

**Comment by gexclaude** [comment]
IMHO the correct repository mischa intended to mention is https://github.com/swagger-api/swagger-ui/tree/master/swagger-ui-dist-package

That is what is being used.

**Comment by derberg** [comment]
hey, please take a look on discussion under https://github.com/asyncapi/asyncapi-react/pull/76
