### ISSUE TITLE
Release 1.0 - why not?

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi-react#761]
Is there any reason why not release v1 "tomorrow" (like merge `next` into `master`)

- We publish release candidates for like almost over 2y I think
- But still `master` is default branch that people read
- CI/CD issues occur as only `master` get updates automatically. This causes maintenance issues and hiccups (like `/rtm` do not work)

cc codeowners @magicmatatjahu @fmvilas

---
Is there anyone having an argument against it?

**Comment by fmvilas** [comment]
Nope. All for it 👍

**Comment by magicmatatjahu** [comment]
yeah, We can publish :)

**Comment by GreenRover** [comment]
I would love this to!

**Comment by jonaslagoni** [comment]
The playground is currently not working on `next`, I have tried to fix it for a week now, but this obscure `react-app-rewired` and it's build system is just not playing ball at all...

**Comment by jonaslagoni** [comment]
> The playground is currently not working on next, I have tried to fix it for a week now, but this obscure react-app-rewired and it's build system is just not playing ball at all...

It's funny, as soon as I write this, I re-tested an implementation I did last week, and now everything magically works.

**Comment by jonaslagoni** [comment]
After playground is fixed I would release the library as v1 for sure 👍

**Comment by derberg** [comment]
once we have https://github.com/asyncapi/asyncapi-react/pull/767 merged, I think we are ready to go with v1 release

**Comment by derberg** [comment]
@magicmatatjahu @fmvilas https://github.com/asyncapi/asyncapi-react/pull/764 is ready for final review. Merge conflicts solved. Playground works. Tests pass. I think we are ready to go. In case of issues, we can always do a followup fixes 🤷🏼

**Comment by derberg** [comment]
it is out https://github.com/asyncapi/asyncapi-react/releases/tag/v1.0.1
