### ISSUE TITLE
Is there a way to show the editor along with the UI (like AsyncAPI Playground)

### ISSUE THREAD

**Issue by doughjoe77** [asyncapi/asyncapi-react#77]
**Description**

Is it possible to show the editor along with the UI (like AsyncAPI Playground), is their an example that shows how to do that?

**Comment by derberg** [comment]
Hey @doughjoe77,

You mean you would like to have something like https://www.asyncapi.com/asyncapi-react/ (please bear in mind this instance is a bit outdated and doesn't use latest 2.0 version of the component)? Source of the playground is here https://github.com/asyncapi/asyncapi-react/tree/master/playground

**Comment by doughjoe77** [comment]
Hi @derberg ,

That's exactly what I was looking for, is the goal of the React component you are working on is to do that as well or would the editor/viewer end up being a seperate component?

Thanks for the help!

**Comment by derberg** [comment]
@doughjoe77 sorry for the delayed response, lots of things were happening recently.

current goal is...but we are opened for other ideas of course:
- https://github.com/asyncapi/asyncapi-react/tree/master/playground stays as it is and we keep it as it is, always up to date as it is a helper for us for the development
- https://www.asyncapi.com/asyncapi-react/ will no longer be there, as you can see it is already outdated. - plan is to have this react component also integrated here https://playground.asyncapi.io/ (you can see there `React (coming soon)` - we have issue for that https://github.com/asyncapi/asyncapi-react/issues/66 but not much time to do it, would be awesome to get some help here

what do you think?

**Comment by derberg** [comment]
@doughjoe77 do you have any opinions or should we just close this one?
