### ISSUE TITLE
Unexpected empty block

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/asyncapi-react#787]
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_asyncapi-react&open=AYrVnL27i9mf_H5ePyyT&tab=why

## Where's the issue? 
- https://sonarcloud.io/code?id=asyncapi_asyncapi-react&selected=asyncapi_asyncapi-react%3Alibrary%2Fsrc%2Fstyles%2Fdefault.css&line=12
-   https://sonarcloud.io/code?id=asyncapi_asyncapi-react&selected=asyncapi_asyncapi-react%3Alibrary%2Fsrc%2Fstyles%2Fdefault.css&line=19
- https://sonarcloud.io/code?id=asyncapi_asyncapi-react&selected=asyncapi_asyncapi-react%3Alibrary%2Fsrc%2Fstyles%2Fdefault.css&line=60

**Comment by parasss19** [comment]
hey @AceTheCreator I want to work on this issue Please assign me this issue

**Comment by AceTheCreator** [comment]
Hey @parasss19, we don't assign issues. Go ahead and work on it :)

**Comment by parasss19** [comment]
> Hey @parasss19, we don't assign issues. Go ahead and work on it :)

hey please also provide labels like hacktoberfest2023, hacktoberfest-accepted on issues and my pr so that it would be accepted in hacktoberfest
