### ISSUE TITLE
Error in web component - Uncaught TypeError: Cannot read properties of undefined (reading 'alloc')

### ISSUE THREAD

**Issue by Bizordec** [asyncapi/asyncapi-react#813]
**Description**

AsyncAPI web component is not working on the latest versions, this error is shown in the console:
![image](https://github.com/asyncapi/asyncapi-react/assets/25798995/a8df8370-95dd-4548-b364-91ace38d2d2a)

**Expected result**

Web component is rendered.

**Actual result**

A white screen is shown.

**Steps to reproduce**

Create an `index.html` file with this content and open it in the browser:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>1.0.2</title>
  </head>
  <body>
    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.8.0/webcomponents-bundle.js"></script>
    <script
      src="https://unpkg.com/@asyncapi/web-component@1.0.2/lib/asyncapi-web-component.js"
      defer
    ></script>

    <asyncapi-component
      schemaUrl="https://raw.githubusercontent.com/asyncapi/spec/v2.6.0/examples/streetlights-kafka.yml"
      config='{"show": {"info": false}}'
      schemaFetchOptions='{"method":"GET","mode":"cors"}'
      cssImportPath="https://unpkg.com/@asyncapi/react-component@1.0.2/styles/default.min.css"
    >
    </asyncapi-component>
  </body>
</html>
```
Or open it in CodeSandbox:
https://codesandbox.io/s/thirsty-kowalevski-gsctyj?file=/index.html

**Troubleshooting**

Rollback to 1.0.0-next.48 version.

**Comment by derberg** [comment]
I can't figure out why it got broken other than refresh of dependencies that we had to do.
Maybe the only solution is hammer, and switch from current package that generated web component from react, to something that is more regularly maintained -https://www.npmjs.com/package/react-to-webcomponent
