### ISSUE TITLE
Reversed pub/sub action render?

### ISSUE THREAD

**Issue by skonik** [asyncapi/asyncapi-react#815]
**Description**

It seems that `subscribe` now renders as `pub` action.

<img width="1681" alt="Screenshot 2023-10-12 at 13 39 51" src="https://github.com/asyncapi/asyncapi-react/assets/50069473/f3f91050-25f1-4d81-8963-5284b14174b3">

**Expected result**

`subscribe` action renders as `sub`.

**Actual result**

`subscribe` action renders as `pub`.

**Steps to reproduce**

Open https://asyncapi.github.io/asyncapi-react/ and scroll down to first subscribe definition in asyncapi file.

**Troubleshooting**

**Comment by derberg** [comment]
yeah, I think you're right, not sure though what is wrong as in the code we did not do the flip, but we did start using new parser that might do the flip

**Comment by ly29** [comment]
I think long term I would made sense to have 2.x and 3.x as separate thing since theese bugs keeps occuring

**Comment by fmvilas** [comment]
This bug has nothing to do with v2 or v3 but with the way we're using the parser. It's just something normal that during the migration to the new parser something go wrong. It shouldn't happen again in the future or it's very unlikely.

**Comment by derberg** [comment]
closing as solved with https://github.com/asyncapi/asyncapi-react/pull/795
