### ISSUE TITLE
HTML anchor broken on sidebar

### ISSUE THREAD

**Issue by hk-ng** [asyncapi/asyncapi-react#830]
**Description**

In sidebar, HTML anchor link to operation seems link to unknown id.

**Expected result**

After clicking HTML anchor link on side bar, browser should to open related operation.

**Actual result**

After clicking HTML anchor link on side bar, URL change and nothing happened.

**Steps to reproduce**

- open <https://asyncapi.github.io/asyncapi-react/>
- fetch url from <https://www.asyncapi.com/resources/casestudies/adeo/asyncapi.yaml>
- Click link `SUB
[COSTING] Request one or more Costing calculation for any product`

**Troubleshooting**

**Comment by Min2who** [comment]
can i work on this issue?

**Comment by devilkiller-ag** [comment]
Hi Can I work on this issue?

**Comment by jonaslagoni** [comment]
No need to ask @Min2who @devilkiller-ag 🙂

**Comment by Santhoshmani1** [comment]
Hi @jonaslagoni 
I would like to work on this issue.

**Comment by christianrowlands** [comment]
Just posting for completeness (to cause the tickets to link), but this issue seem to be the root cause of one of the two bugs from this ticket: https://github.com/asyncapi/html-template/issues/464
