### ISSUE TITLE
Feat: React children components support

### ISSUE THREAD

**Issue by Lancetnik** [asyncapi/asyncapi-react#840]
Hello there! I am a core developer of [FastStream](https://github.com/airtai/faststream) - the Python frameworks to build well-structured publish/consumes services for various Message Brokers. One of the great FastStream features users love - automatic AsyncAPI schema generation (and hosting) right from the service code. Thus, I have a little request to you.

For now, FastStream uses CDN React Component version to draw a static HTML represention of user service schema. But we can easely (cuz we have backend to serve this static site) implement test message publishing funtional right from a web schema (like OpenAPI allows you to send test HTTP requests). At first, test messages will be addressed only to the original FastStream service... But then we'll implement AsyncAPI schema -> FastStream service generation, that allows us to generate publishers "on flyight" and publish any message to any FastStream-supported Message Broker right from the website.

A slightly confusing preface... We need to ability pass some React-children components to the AsyncAPI react component to draw user payload input somewhere around payload example. We can create the component fork and implement our own component version (with all required inputs), but it is a bad way to build long-living tools. So, I hope on your team collaboration in this question and believe, that together we able to make AsyncAPI environment riacher.

**Comment by jonaslagoni** [comment]
I agree, the components should be as extensible and overwritable as possible 👌

**Comment by derberg** [comment]
@Lancetnik please just share in more details what changes you will exactly introduce and definitely we are open to accept any PR that will make the component more flexible and extensible. We are even open to gain you as maintainers

**Comment by devilkiller-ag** [comment]
Hi, I am a bit curious about this discussion, but I am finding it a little difficult to understand. I will try to explore the async api react component in the upcoming weeks and update you all regarding this. It will be helpful if @Lancetnik can provide more details.

**Comment by Lancetnik** [comment]
<img width="516" alt="Снимок экрана 2023-12-20 в 20 54 35" src="https://github.com/asyncapi/asyncapi-react/assets/44573917/bc1e7080-66e4-4230-99f1-1039e6b393e1">

Here is a payload example component of AsyncAPI schema. This webpage is generated automatically by **FastStream** by passing AsyncAPI `json/yaml` schema to react component. But we are interested to make this page interactive by adding "Try it out" btn to make this payload textfield editable and and make user able to publish a test message right to the broker like OpenAPI does.

Exactly in this case, probably, we can add a props to propogate it to the [MessageExample](https://github.com/asyncapi/asyncapi-react/blob/master/library/src/containers/Messages/MessageExample.tsx) as a child instead this [div](https://github.com/asyncapi/asyncapi-react/blob/master/library/src/containers/Messages/MessageExample.tsx#L107).

But it will be great to create public React components to provides your library users with making their own full-extendable [AsyncAPILayout](https://github.com/asyncapi/asyncapi-react/blob/master/library/src/containers/AsyncApi/Layout.tsx)
