### ISSUE TITLE
Cannot build on linux: sh: 1: cross-env: not found. And when installing cross-env globally: Error: spawn postcss ENOENT

### ISSUE THREAD

**Issue by ghuser** [asyncapi/asyncapi-react#841]
**Description**

I am trying to build the component.
I have cloned he repository.
switched to tag: v1.2.2
npm install

**Expected result**

npm install completes

**Actual result**

`sh: 1: cross-env: not found`

And when I try to install globally ( `npm i -g cross-env` ) I get:

```
> @asyncapi/react-component@1.2.2 build:styles:dev
> cross-env NODE_ENV=production postcss src/styles/default.css -o styles/default.css --verbose

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn postcss ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn postcss',
  path: 'postcss',
  spawnargs: [ 'src/styles/default.css', '-o', 'styles/default.css', '--verbose' ]
}
```

**Steps to reproduce**

**Troubleshooting**

**Comment by derberg** [comment]
please confirm if the issue is still there in version 1.2.11

I see cross-env is added as dependency in `library`

**Comment by ghuser** [comment]
In v1.2.11 I had to install webpack with `npm i -g webpack`. Then after using `npm i` (node-modules cleaned and other changed files reverted) the process freezes in the following point: 

![image](https://github.com/asyncapi/asyncapi-react/assets/672768/df189702-8f97-43a7-aa13-47b783c0dedf)
