### ISSUE TITLE
Subscription and publication are mixed up in places

### ISSUE THREAD

**Issue by OboyaShka** [asyncapi/asyncapi-react#858]
Hello! 

I have the following this versions of your libraries connected and the places pub and sub are mixed up in the view scheme, but in yours playground all is fine. Can u help, which dependency should I update to make everything work as it should?

In my case
![image](https://github.com/asyncapi/asyncapi-react/assets/66056854/a402e58c-7bec-4259-8b6b-e991a52c4dd1)

On your playground
![image](https://github.com/asyncapi/asyncapi-react/assets/66056854/2fd841b5-85f4-4048-b2ef-ca67b66224f2)

  "@asyncapi/react-component": {
    ".": "1.2.4",
    "@asyncapi/parser": "3.0.0",
    "@asyncapi/openapi-schema-parser": "3.0.6",
    "@asyncapi/avro-schema-parser": "3.0.6",
    "@asyncapi/specs": "6.0.0",
    "@asyncapi/protobuf-schema-parser": "3.0.0"
  }

**Comment by derberg** [comment]
Please share your asyncapi document so we can confirm
