### ISSUE TITLE
Option "errors: true" shows empty/blank page when document has errors

### ISSUE THREAD

**Issue by ivangsa** [asyncapi/asyncapi-react#874]
**Description**

As reported in VSCode AsyncAPI Preview:
https://github.com/asyncapi/vs-asyncapi-preview/issues/200

After upgrading to latest: `"@asyncapi/react-component": "^1.2.7"`

It shows a blank page when document contains validation errors

This are the configuration options used:
<img width="371" alt="image" src="https://github.com/asyncapi/asyncapi-react/assets/1246876/22a4834d-2084-4dfa-b526-abcf3cf776d2">

**Comment by ashmit-coder** [comment]
hey @ivangsa 
The issue seems to occur due to unhandled undefined  of the document object
    
    try {
          const { document } = await asyncapiParser.parse(content, parserOptions);
          return { asyncapi: document };
        } catch (err) {
          return this.handleError(err as ErrorObject);
        }

Here the document object turns out undefined and hence no error is thrown.
    
    try {
          const parseResult = await asyncapiParser.parse(content, parserOptions);
    
          let error:({title:string} ) = {title:""};
          if(parseResult.document === undefined) {
    
            parseResult.diagnostics.forEach(diagnostic => {
              if(diagnostic.code.toString().includes("error")) {
                error.title = diagnostic.message.toString();
              }
            });
    
            if(error.title === "") {
              error.title = "Unexpected error while parsing the document.";
            }
    
            throw error;
          }
    
          return { asyncapi: parseResult.document };
        } catch (err) {
          return this.handleError(err as ErrorObject);
        }

This is one way we could resolve this issue.

I will draft a PR for the same and we can communicate over it.

**Comment by ashmit-coder** [comment]
Hey @derberg if you may help guide through this it will be great.

**Comment by ashmit-coder** [comment]
This maybe an upstream error as the parser does not throw an error as of the latest version but rather an undefined document object witth a error message in the diganostic object
