### ISSUE TITLE
Can't use any recent version

### ISSUE THREAD

**Issue by Andrzejczyk97** [asyncapi/asyncapi-react#878]
Can someone show me a sandbox/repo where react-component is used in a simple example. There is a sandbox in README, but its based on an old release and using the new one like that one don't work.

**Expected result**
Sandbox that will show how to use the current version of the react-component

**Actual result**

If You upgrade the lib to new version(current sandbox is on 0.24.x v) it won't work. I can't get it to work anyhow.

**Comment by derberg** [comment]
Can you specify what errors are you getting? the component latest version is used successfully in https://studio.asyncapi.com/

**Comment by derberg** [comment]
no response, closing

open new issue if problem is still there
