### ISSUE TITLE
Update the Playground Text Editor Scrollbar

### ISSUE THREAD

**Issue by nikhilkalburgi** [asyncapi/asyncapi-react#880]
**Description**

Change the scrollbar

**Reasons**

It does not match with background of the text editor

**Attachments**
![image](https://github.com/asyncapi/asyncapi-react/assets/70331875/17116703-6ae5-4861-91b5-5619edbbc443)

**Comment by derberg** [comment]
Thanks but playground is a simple, and should be as simple as possible, tool just for development purposes, any additional nice to have feature would not help in long term maintainance.

if you wanna help with web dev please join: https://github.com/asyncapi/conference-website/
