### ISSUE TITLE
update project dependencies

### ISSUE THREAD

**Issue by vishvamsinh28** [asyncapi/asyncapi-react#891]
This issue aims to update the project dependencies, encompassing the latest Node.js version, npm or Yarn updates, and the upgrading of project dependencies to their latest compatible versions.

**Comment by kennethaasan** [comment]
Just realized that this project needs Node v16 which is now dead. It fails when you try to start it with Node v18. We need this project to support >= v18

**Comment by kennethaasan** [comment]
- [ ] migrate from react-scripts to next.js: #929 
- [ ] migrate from tslint to eslint
- [ ] upgrade react.js to v18 in the library
- [ ] upgrade dependencies

**Comment by derberg** [comment]
reopenning
looks like this issue was marked as being resolved with playground PR - but that is not the case yet

**Comment by derberg** [comment]
@kennethaasan will you proceed with other tasks?

**Comment by kennethaasan** [comment]
Yes, that's the plan. I'll get to it in April/May.
