### ISSUE TITLE
Sidebar broken in playground when preview switches to compact layout

### ISSUE THREAD

**Issue by rijenkii** [asyncapi/asyncapi-react#907]
**Description**

When opening the sidebar through the hamburger button on bottom right of the screen, it is drawn on the right border of the screen, or not drawn at all if you decrease the space dedicated to the preview.

Reproduced on Firefox 121 and Chromium 120.0.6099.216, Fedora 39.

**Steps to reproduce**

Paste the following into the [playground](https://asyncapi.github.io/asyncapi-react/):

<details><summary>Schema</summary>

```json
{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Reproduction",
    "version": "1.0.0"
  },
  "operations": {
    "test": {
      "action": "receive",
      "channel": { "$ref": "#/channels/test" }
    }
  },
  "channels": {
    "test": {
      "address": "/test",
      "messages": {
        "test": { "$ref": "#/components/messages/test" }
      }
    }
  },
  "components": {
    "messages": {
      "test": {
        "payload": {
          "type": "object",
          "properties": {
            "test": {
              "description": "test",
              "type": "string",
              "pattern": "^(?:helloworld)+$"
            }
          },
          "required": ["test"]
        }
      }
    }
  }
}
```

</details>

<details><summary>Configuration</summary>

```json
{
  "show": {
    "sidebar": true,
    "info": true,
    "operations": true,
    "servers": true,
    "messages": true,
    "schemas": true,
    "errors": true
  },
  "expand":{
    "messageExamples": false
  },
  "sidebar": {
    "showServers": "byDefault",
    "showOperations": "byDefault"
  }
}
```

</details>

Then click on the hamburger button.

**Expected result**

![image](https://github.com/asyncapi/asyncapi-react/assets/5338332/bf48b69c-051b-433a-bce3-a2e325c9d599)

**Actual result**

![image](https://github.com/asyncapi/asyncapi-react/assets/5338332/9863a6af-7e8a-4d69-a39b-0d47e03d26be)

**Troubleshooting**

I have achieved the result in the "expected result" by removing `.w-full` from the parent of `.sidebar--content` and hardcoding correct width on that element.

**Comment by rijenkii** [comment]
Still an issue.

**Comment by kash2104** [comment]
@rijenkii is the issue still open?

**Comment by rijenkii** [comment]
The issue is still reproducible on https://asyncapi.github.io/asyncapi-react/:
![image](https://github.com/user-attachments/assets/30370e12-1a21-4a64-a447-b3f21139a1b1)
