### ISSUE TITLE
Support displaying enums

### ISSUE THREAD

**Issue by hesyar** [asyncapi/asyncapi-react#93]
**Description**

When enums are used within the spec file, they are not displayed. 
As we provide enums like following:
![image](https://user-images.githubusercontent.com/35898/78560286-2eeb2f00-7816-11ea-8882-44ca52997372.png)

We would expected here enums to be shown like in the generator itself but rather get the following:
![image](https://user-images.githubusercontent.com/35898/78560300-37436a00-7816-11ea-8306-c50ae4db8bc4.png)

**Reasons**

We want to be able to see enums in the component

**Attachments**

**Comment by GreenRover** [comment]
+1
