### ISSUE TITLE
additionalProperties: {} or false not supported properly

### ISSUE THREAD

**Issue by hesyar** [asyncapi/asyncapi-react#94]
**Description**

As we use additionalProperties as follow: additonalProperties: false we get the following error message:

![image](https://user-images.githubusercontent.com/35898/78561932-d10c1680-7818-11ea-8f07-96e1373ef8b9.png)

As we change this to additionalProperties: {} it doesn't throw any errors anymore but ignores the property completely and doesn't any indicator that additional properties aren't allowed.

**Expected result**

An indicator that like the generator for example like this: 
![image](https://user-images.githubusercontent.com/35898/78562445-a40c3380-7819-11ea-959d-f51fcf493b2c.png) and "Additional properties are not allowed"

**Actual result**

Nothing. Completely ignores this properties

**Comment by GreenRover** [comment]
+1

**Comment by fmvilas** [comment]
Starting to work on this one now.
