### ISSUE TITLE
Title column is shown eventhough no title is given

### ISSUE THREAD

**Issue by hesyar** [asyncapi/asyncapi-react#95]
**Description**

In the async component table a title column is display although nowhere a title was given.
![image](https://user-images.githubusercontent.com/35898/78562682-0c5b1500-781a-11ea-8727-514733c98866.png)

**Expected result**

When the title column has no content, it should be hidden.

**Actual result**

An empty title column appears.

**Comment by GreenRover** [comment]
+1
