### ISSUE TITLE
Regex pattern not displayed behind the property type

### ISSUE THREAD

**Issue by hesyar** [asyncapi/asyncapi-react#96]
**Description**

Regex pattern are not displayed in the description of the properties.

**Expected result**
Regex Pattern should be displayed behind the type of the property like it is in the generator. e.x.

![image](https://user-images.githubusercontent.com/35898/78563004-92775b80-781a-11ea-90db-2b52dd2172ec.png)

**Actual result**

Regex pattern is ignored completely see:
![image](https://user-images.githubusercontent.com/35898/78563018-97d4a600-781a-11ea-8039-bd18a2265a12.png)

**Steps to reproduce**

Use somewhere regex patterns in your spec file

**Comment by GreenRover** [comment]
+1
