### ISSUE TITLE
508 Accessibility: Opening content in a new window

### ISSUE THREAD

**Issue by ghost** [asyncapi/asyncapi-react#962]
We use a tool called Sort Site to evaluate our site for Section 508 Accessibility.  It is flagging that links to content either should not open in a new window or else should inform users that the content will be opened in a new window.  The error information is:  

![image](https://github.com/asyncapi/asyncapi-react/assets/86489380/7e92efc9-08ba-4179-bb20-8c6ec2437177)

The source of these errors on our page is the APPLICATION/XML and EXTERNAL DOCS links:
![image](https://github.com/asyncapi/asyncapi-react/assets/86489380/a1c3fde1-8f28-4623-8c4d-4f2c83dcc579)

Either these links should display the content in the same window, or there should be text like "(opens in a new window)" with the links.

**Comment by aakankshabhende** [comment]
@ghost I would like to work on this issue. Could you please assign me this?

**Comment by AceTheCreator** [comment]
@aakankshabhende, we don't assign issues, feel free to pick it up :)
