### ISSUE TITLE
Incorrect rendering of security schemas: by reference and inline

### ISSUE THREAD

**Issue by Amzani** [asyncapi/asyncapi-react#993]
Original issue reported by @RobinTail 
https://github.com/asyncapi/studio/issues/1066

**Comment by RobinTail** [comment]
The issue is within there lines, @Amzani :

https://github.com/RobinTail/asyncapi-react/blob/77d77c476269d3fd8c4773071375e3046a4bb09b/library/src/containers/Servers/Security.tsx#L42-L43

**Comment by RobinTail** [comment]
Perhaps it's because of the differences between AsyncAPI 2.6 and 3.0
